return {
  AOSC = {
    color = "#c00000",
    icon = "linux-aosc",
    os = { "aosc" },
  },
  Ai = {
    color = "#cbcb41",
    extension = { "ai" },
    icon = "dev-illustrator",
  },
  Almalinux = {
    color = "#ff4649",
    icon = "linux-almalinux",
    os = { "alma" },
  },
  Alpine = {
    color = "#0d597f",
    icon = "linux-alpine",
    os = { "alpine" },
  },
  Apple = {
    color = "#A2AAAD",
    icon = "seti-apple",
    os = { "apple" },
  },
  AppleScript = {
    color = "#6d8085",
    extension = { "applescript" },
    filetype = { "applescript" },
    icon = "fa-apple",
  },
  Arch = {
    color = "#0f94d2",
    icon = "md-arch",
    os = { "arch" },
  },
  Arduino = {
    color = "#56b6c2",
    extension = { "ino" },
    filetype = { "arduino" },
    icon = "linux-arduino",
  },
  Artix = {
    color = "#41b4d7",
    icon = "linux-artix",
    os = { "artix" },
  },
  Audio = {
    color = "#66D8EF",
    extension = { "aac", "flac", "mp3", "m4a", "ogg", "wav" },
    icon = "fa-music",
  },
  AzureCli = {
    color = "#0078d4",
    extension = { "azcli" },
    icon = "cod-azure_devops",
  },
  Backup = {
    color = "#6d8086",
    extension = { "bak" },
    icon = "md-backup_restore",
  },
  Bash = {
    color = "#89e051",
    extension = { "bash" },
    filetype = { "bash" },
    icon = "dev-terminal",
  },
  BashConfig = {
    color = "#89e051",
    file = { ".bash_profile", ".bashrc" },
    icon = "seti-config",
  },
  Bat = {
    color = "#C1F12E",
    extension = { "bat" },
    filetype = { "winbatch", "dosbatch" },
    icon = "seti-config",
  },
  Bazel = {
    color = "#89e051",
    extension = { "bzl", "bazel" },
    file = { "build", "workspace" },
    filetype = { "bzl" },
    icon = "seti-bazel",
  },
  BibTeX = {
    color = "#cbcb41",
    extension = { "bib" },
    filetype = { "bib" },
    icon = "md-bookshelf",
  },
  BinaryGLTF = {
    color = "#FFB13B",
    extension = { "glb" },
    icon = "fa-cube",
  },
  Brewfile = {
    color = "#701516",
    file = { "brewfile" },
    icon = "dev-ruby_rough",
  },
  Budgie = {
    color = "#5195e3",
    icon = "linux-budgie",
    os = { "budgie" },
  },
  C = {
    color = "#599eff",
    extension = { "c" },
    filetype = { "c" },
    icon = "custom-c",
  },
  CMake = {
    color = "#6d8086",
    extension = { "cmake" },
    file = { "cmakelists.txt" },
    filetype = { "cmake" },
    icon = "seti-config",
  },
  CPlusPlus = {
    color = "#f34b7d",
    extension = { "c++", "cc", "ccm" },
    icon = "custom-cpp",
  },
  CSharpProject = {
    color = "#512bd4",
    extension = { "csproj" },
    icon = "md-dot_net",
  },
  Centos = {
    color = "#a2518d",
    icon = "linux-centos",
    os = { "centos" },
  },
  Checkhealth = {
    color = "#75B4FB",
    file = { "checkhealth" },
    filetype = { "checkhealth" },
    icon = "md-stethoscope",
  },
  Clojure = {
    color = "#8dc149",
    extension = { "clj" },
    filetype = { "clojure" },
    icon = "dev-clojure",
  },
  ClojureC = {
    color = "#8dc149",
    extension = { "cljc" },
    icon = "dev-clojure",
  },
  ClojureDart = {
    color = "#519aba",
    extension = { "cljd" },
    icon = "dev-clojure_alt",
  },
  ClojureJS = {
    color = "#519aba",
    extension = { "cljs" },
    icon = "dev-clojure_alt",
  },
  Cobol = {
    color = "#005ca5",
    extension = { "cob", "cobol", "cpy", "cbl" },
    filetype = { "cobol" },
    icon = "⚙",
  },
  Coffee = {
    color = "#cbcb41",
    extension = { "coffee" },
    filetype = { "coffee" },
    icon = "seti-coffee",
  },
  Conf = {
    color = "#6d8086",
    extension = { "conf" },
    filetype = { "conf" },
    icon = "seti-config",
  },
  Configuration = {
    color = "#ECECEC",
    extension = { "cfg" },
    filetype = { "cfg" },
    icon = "dev-code_badge",
  },
  Cp = {
    color = "#519aba",
    extension = { "cp", "cpp", "cxx", "cppm", "cxxm", "ixx", "mpp" },
    filetype = { "cpp" },
    icon = "custom-cpp",
  },
  Crystal = {
    color = "#c8c8c8",
    extension = { "cr" },
    filetype = { "crystal" },
    icon = "custom-crystal",
  },
  Cs = {
    color = "#596706",
    extension = { "cs" },
    filetype = { "cs" },
    icon = "md-language_csharp",
  },
  Cson = {
    color = "#cbcb41",
    extension = { "cson" },
    filetype = { "cson" },
    icon = "seti-less",
  },
  Css = {
    color = "#42a5f5",
    extension = { "css" },
    filetype = { "css" },
    icon = "dev-css3",
  },
  Csv = {
    color = "#89e051",
    extension = { "csv" },
    filetype = { "csv" },
    icon = "seti-csv",
  },
  Cuda = {
    color = "#89e051",
    extension = { "cu" },
    filetype = { "cuda" },
    icon = "seti-cu",
  },
  Cudah = {
    color = "#a074c4",
    extension = { "cuh" },
    icon = "seti-cu",
  },
  Cython = {
    color = "#5aa7e4",
    extension = { "pxd", "pxi", "pyx" },
    icon = "seti-python",
  },
  D = {
    color = "#427819",
    extension = { "d" },
    filetype = { "d" },
    icon = "dev-dlang",
  },
  Dart = {
    color = "#03589C",
    extension = { "dart" },
    filetype = { "dart" },
    icon = "dev-dart",
  },
  Db = {
    color = "#dad8d8",
    extension = { "db", "dump", "sql", "sqlite", "sqlite3" },
    filetype = { "sql", "mysql" },
    icon = "dev-database",
  },
  Debian = {
    color = "#a80030",
    icon = "linux-debian",
    os = { "debian" },
  },
  Deepin = {
    color = "#2ca7f8",
    icon = "linux-deepin",
    os = { "deepin" },
  },
  DesktopEntry = {
    color = "#563d7c",
    extension = { "desktop" },
    filetype = { "desktop" },
    icon = "fa-desktop",
  },
  Devuan = {
    color = "#404a52",
    icon = "linux-devuan",
    os = { "devuan" },
  },
  Diff = {
    color = "#41535b",
    extension = { "diff" },
    filetype = { "diff" },
    icon = "dev-git_compare",
  },
  Dockerfile = {
    color = "#458ee6",
    extension = { "Dockerfile" },
    file = {
      ".dockerignore",
      "compose.yaml",
      "compose.yml",
      "containerfile",
      "dockerfile",
      "docker-compose.yaml",
      "docker-compose.yml",
    },
    filetype = { "dockerfile" },
    icon = "md-docker",
  },
  Drools = {
    color = "#ffafaf",
    extension = { "drl" },
    icon = "fae-brain",
  },
  Dropbox = {
    color = "#0061FE",
    extension = { "dropbox" },
    icon = "dev-dropbox",
  },
  DsStore = {
    color = "#41535b",
    file = { ".ds_store" },
    icon = "seti-config",
  },
  EditorConfig = {
    color = "#fff2f2",
    file = { ".editorconfig" },
    filetype = { "editorconfig" },
    icon = "seti-editorconfig",
  },
  Edn = {
    color = "#519aba",
    extension = { "edn" },
    icon = "dev-clojure_alt",
  },
  Ejs = {
    color = "#cbcb41",
    extension = { "ejs" },
    filetype = { "ejs" },
    icon = "seti-html",
  },
  Elementary = {
    color = "#5890c2",
    icon = "linux-elementary",
    os = { "elementary" },
  },
  Elm = {
    color = "#519aba",
    extension = { "elm" },
    filetype = { "elm" },
    icon = "custom-elm",
  },
  Endeavour = {
    color = "#7b3db9",
    icon = "linux-endeavour",
    os = { "endeavour" },
  },
  Env = {
    color = "#faf743",
    file = { ".env" },
    icon = "oct-sliders",
  },
  Epp = {
    color = "#FFA61A",
    extension = { "epp" },
    icon = "seti-puppet",
  },
  Erb = {
    color = "#701516",
    extension = { "erb" },
    icon = "seti-html",
  },
  Erl = {
    color = "#B83998",
    extension = { "erl", "hrl" },
    filetype = { "erlang" },
    icon = "dev-erlang",
  },
  Eslint = {
    color = "#4b32c3",
    file = { ".eslintignore", ".eslintrc" },
    icon = "seti-eslint",
  },
  Ex = {
    color = "#a074c4",
    extension = { "ex", "exs", "eex", "leex", "heex" },
    file = { "mix.lock" },
    filetype = { "elixir" },
    icon = "custom-elixir",
  },
  Excel = {
    color = "#207245",
    extension = { "xls", "xlsx" },
    icon = "md-file_excel",
  },
  Exe = {
    color = "#9F0500",
    extension = { "app", "elf", "exe", "out" },
    icon = "cod-file_binary",
  },
  FSharp = {
    color = "#519aba",
    extension = { "fs", "f#", "fsi", "fsscript", "fsx" },
    filetype = { "fsharp" },
    icon = "dev-fsharp",
  },
  Favicon = {
    color = "#cbcb41",
    file = { "favicon.ico" },
    icon = "seti-favicon",
  },
  Fedora = {
    color = "#072a5e",
    icon = "linux-fedora",
    os = { "fedora" },
  },
  Fennel = {
    color = "#fff3d7",
    extension = { "fnl" },
    filetype = { "fennel" },
    icon = "custom-fennel",
  },
  Font = {
    color = "#ECECEC",
    extension = { "eot", "otf", "ttf", "woff", "woff2" },
    icon = "fa-font",
  },
  Fortran = {
    color = "#734f96",
    extension = { "f90" },
    filetype = { "fortran" },
    icon = "md-language_fortran",
  },
  FreeBSD = {
    color = "#c90f02",
    icon = "linux-freebsd",
    os = { "freebsd" },
  },
  GDScript = {
    color = "#6d8086",
    extension = { "gd" },
    filetype = { "gdscript" },
    icon = "seti-config",
  },
  Gentoo = {
    color = "#b1abce",
    icon = "md-gentoo",
    os = { "gentoo" },
  },
  Git = {
    color = "#41535b",
    file = { ".gitattributes", "commit_editmsg", ".gitignore", ".gitmodules" },
    filetype = { "gitcommit", "gitignore", "gitattributes" },
    icon = "dev-git",
  },
  GitConfig = {
    color = "#41535b",
    file = { ".gitconfig" },
    filetype = { "gitconfig" },
    icon = "seti-config",
  },
  GitLogo = {
    color = "#F14C28",
    extension = { "git" },
    icon = "dev-git",
  },
  GitlabCI = {
    color = "#e24329",
    file = { ".gitlab-ci.yml" },
    icon = "fa-gitlab",
  },
  Go = {
    color = "#519aba",
    extension = { "go" },
    filetype = { "go" },
    icon = "seti-go",
  },
  GodotProject = {
    color = "#6d8086",
    extension = { "godot" },
    icon = "dev-code_badge",
  },
  GraphQL = {
    color = "#e535ab",
    extension = { "gql", "graphql" },
    filetype = { "graphql" },
    icon = "fa-connectdevelop",
  },
  Groovy = {
    color = "#4a687c",
    file = { "groovy" },
    filetype = { "groovy" },
    icon = "dev-groovy",
  },
  Gruntfile = {
    color = "#e37933",
    file = { "gruntfile" },
    icon = "seti-grunt",
  },
  Guix = {
    color = "#ffcc00",
    icon = "linux-gnu_guix",
    os = { "guix" },
  },
  Gulpfile = {
    color = "#cc3e44",
    file = { "gulpfile" },
    icon = "seti-gulp",
  },
  H = {
    color = "#a074c4",
    extension = { "h", "hh", "hpp", "hxx" },
    icon = "fa-h_square",
  },
  Haml = {
    color = "#eaeae1",
    extension = { "haml" },
    filetype = { "haml" },
    icon = "seti-html",
  },
  Haxe = {
    color = "#ea8220",
    extension = { "hx" },
    filetype = { "haxe" },
    icon = "seti-haxe",
  },
  Hbs = {
    color = "#f0772b",
    extension = { "hbs" },
    filetype = { "html.handlebars" },
    icon = "seti-mustache",
  },
  Hs = {
    color = "#a074c4",
    extension = { "hs", "lhs" },
    filetype = { "haskell" },
    icon = "seti-haskell",
  },
  Htm = {
    color = "#e34c26",
    extension = { "htm" },
    icon = "seti-html",
  },
  Html = {
    color = "#e44d26",
    extension = { "html" },
    filetype = { "html" },
    icon = "dev-html5",
  },
  Huff = {
    color = "#4242c7",
    extension = { "huff" },
    filetype = { "huff" },
    icon = "md-chess_knight",
  },
  Hurl = {
    color = "#ff0288",
    extension = { "hurl" },
    filetype = { "hurl" },
    icon = "fa-exchange",
  },
  Ico = {
    color = "#cbcb41",
    extension = { "ico" },
    icon = "seti-image",
  },
  Illumos = {
    color = "#ff430f",
    icon = "linux-illumos",
    os = { "illumos" },
  },
  ImportConfiguration = {
    color = "#ECECEC",
    extension = { "import" },
    filetype = { "import" },
    icon = "fa-paperclip",
  },
  Ini = {
    color = "#6d8086",
    extension = { "ini" },
    filetype = { "ini" },
    icon = "seti-config",
  },
  Java = {
    color = "#cc3e44",
    extension = { "java" },
    filetype = { "java" },
    icon = "dev-java",
  },
  JavaScriptReactTest = {
    color = "#20c2e3",
    extension = { "spec.jsx", "test.jsx" },
    icon = "oct-beaker",
  },
  Jl = {
    color = "#a270ba",
    extension = { "jl" },
    filetype = { "julia" },
    icon = "seti-julia",
  },
  Js = {
    color = "#F1F134",
    extension = { "js", "cjs", "mjs" },
    filetype = { "javascript" },
    icon = "md-language_javascript",
  },
  Json = {
    color = "#cbcb41",
    extension = { "json", "json5", "jsonc" },
    file = { ".babelrc" },
    filetype = { "json", "json5", "jsonc" },
    icon = "seti-less",
  },
  Jsx = {
    color = "#20c2e3",
    extension = { "jsx" },
    filetype = { "javascriptreact" },
    icon = "seti-react",
  },
  Kali = {
    color = "#2777ff",
    icon = "linux-kali_linux",
    os = { "kali" },
  },
  Kotlin = {
    color = "#7F52FF",
    extension = { "kt", "kts" },
    filetype = { "kotlin" },
    icon = "custom-kotlin",
  },
  Less = {
    color = "#563d7c",
    extension = { "less" },
    filetype = { "less" },
    icon = "seti-css",
  },
  License = {
    color = "#cbcb41",
    extension = { "license" },
    file = { "copying.lesser", "unlicense", "license", "copying" },
    icon = "seti-license",
  },
  Linux = {
    color = "#fdfdfb",
    icon = "cod-terminal_linux",
    os = { "linux" },
  },
  Liquid = {
    color = "#95BF47",
    extension = { "liquid" },
    filetype = { "liquid" },
    icon = "seti-liquid",
  },
  Lock = {
    color = "#bbbbbb",
    extension = { "lock" },
    icon = "fa-unlock_alt",
  },
  Log = {
    color = "#dddddd",
    extension = { "log" },
    filetype = { "log" },
    icon = "md-library",
  },
  Lua = {
    color = "#51a0cf",
    extension = { "lua" },
    filetype = { "lua" },
    icon = "seti-lua",
  },
  Luau = {
    color = "#00a2ff",
    extension = { "luau" },
    filetype = { "luau" },
    icon = "seti-lua",
  },
  Luaurc = {
    color = "#00a2ff",
    file = { ".luaurc" },
    icon = "seti-config",
  },
  Mageia = {
    color = "#2397d4",
    icon = "linux-mageia",
    os = { "mageia" },
  },
  Makefile = {
    color = "#6d8086",
    extension = { "makefile", "mk", "gnumakefile" },
    file = { "makefile", "gnumakefile" },
    filetype = { "make" },
    icon = "dev-gnu",
  },
  Manjaro = {
    color = "#33b959",
    icon = "linux-manjaro",
    os = { "manjaro" },
  },
  Markdown = {
    color = "#dddddd",
    extension = { "markdown" },
    filetype = { "markdown" },
    icon = "seti-markdown",
  },
  Material = {
    color = "#B83998",
    extension = { "material" },
    icon = "md-image_filter_hdr",
  },
  Md = {
    color = "#dddddd",
    extension = { "md" },
    icon = "oct-markdown",
  },
  Mdx = {
    color = "#519aba",
    extension = { "mdx" },
    icon = "oct-markdown",
  },
  Mint = {
    color = "#87c095",
    extension = { "mint" },
    icon = "md-leaf",
    os = { "mint" },
  },
  Ml = {
    color = "#e37933",
    extension = { "ml", "mli" },
    filetype = { "ocaml" },
    icon = "seti-ocaml",
  },
  Motoko = {
    color = "#9772FB",
    extension = { "mo" },
    icon = "∞",
  },
  Movie = {
    color = "#FD971F",
    extension = { "m4v", "mkv", "mov", "mp4", "webm" },
    icon = "fa-video_camera",
  },
  Mustache = {
    color = "#e37933",
    extension = { "mustache" },
    filetype = { "html.mustache" },
    icon = "seti-mustache",
  },
  NPM = {
    color = "#E8274B",
    file = { ".npmignore", ".npmrc" },
    icon = "dev-npm",
  },
  Nim = {
    color = "#f3d400",
    extension = { "nim" },
    filetype = { "nim" },
    icon = "seti-nim",
  },
  Nix = {
    color = "#7ebae4",
    extension = { "nix" },
    filetype = { "nix" },
    icon = "linux-nixos",
  },
  NixOS = {
    color = "#7ab1db",
    icon = "linux-nixos",
    os = { "nixos" },
  },
  NodeModules = {
    color = "#E8274B",
    file = { "node_modules" },
    icon = "dev-nodejs_small",
  },
  Notebook = {
    color = "#51a0cf",
    extension = { "ipynb" },
    icon = "seti-python",
  },
  Nswag = {
    color = "#85ea2d",
    extension = { "nswag" },
    icon = "seti-less",
  },
  Nushell = {
    color = "#3aa675",
    extension = { "nu" },
    filetype = { "nu" },
    icon = ">",
  },
  OPUS = {
    color = "#F88A02",
    extension = { "opus" },
    icon = "md-file_music",
  },
  OpenBSD = {
    color = "#f2ca30",
    icon = "linux-openbsd",
    os = { "openbsd" },
  },
  OpenSCAD = {
    color = "#f9d72c",
    extension = { "scad" },
    icon = "linux-openscad",
  },
  OpenSUSE = {
    color = "#6fb424",
    icon = "linux-opensuse",
    os = { "opensuse" },
  },
  OrgMode = {
    color = "#77AA99",
    extension = { "org" },
    filetype = { "org" },
    icon = "custom-orgmode",
  },
  PackageJson = {
    color = "#e8274b",
    file = { "package.json" },
    icon = "dev-npm",
  },
  PackageLockJson = {
    color = "#7a0d21",
    file = { "package-lock.json" },
    icon = "dev-npm",
  },
  PackedResource = {
    color = "#6d8086",
    extension = { "pck" },
    icon = "oct-package",
  },
  Parrot = {
    color = "#54deff",
    icon = "linux-parrot",
    os = { "parrot" },
  },
  Pdf = {
    color = "#b30b00",
    extension = { "pdf" },
    icon = "cod-file_pdf",
  },
  PhotoShop = {
    color = "#519aba",
    extension = { "psb", "psd" },
    icon = "dev-photoshop",
  },
  Php = {
    color = "#a074c4",
    extension = { "php" },
    filetype = { "php" },
    icon = "seti-php",
  },
  Picture = {
    color = "#a074c4",
    extension = { "avif", "bmp", "gif", "jpeg", "jxl", "jpg", "png", "webp" },
    filetype = { "avif", "bmp" },
    icon = "seti-image",
  },
  Pl = {
    color = "#519aba",
    extension = { "pl", "pm" },
    filetype = { "perl" },
    icon = "dev-perl",
  },
  Pop_OS = {
    color = "#48b9c7",
    icon = "linux-pop_os",
    os = { "pop_os" },
  },
  Pp = {
    color = "#FFA61A",
    extension = { "pp" },
    icon = "seti-puppet",
  },
  Ppt = {
    color = "#cb4a32",
    extension = { "ppt" },
    icon = "md-file_powerpoint",
  },
  Prisma = {
    color = "#5a67d8",
    extension = { "prisma" },
    filetype = { "prisma" },
    icon = "seti-prisma",
  },
  Procfile = {
    color = "#a074c4",
    file = { "procfile" },
    filetype = { "procfile" },
    icon = "seti-heroku",
  },
  Prolog = {
    color = "#e4b854",
    extension = { "pro" },
    filetype = { "prolog" },
    icon = "dev-prolog",
  },
  PsManifestfile = {
    color = "#6975c4",
    extension = { "psd1" },
    icon = "md-powershell",
  },
  PsScriptModulefile = {
    color = "#6975c4",
    extension = { "psm1" },
    icon = "md-powershell",
  },
  PsScriptfile = {
    color = "#4273ca",
    extension = { "ps1" },
    filetype = { "ps1" },
    icon = "md-powershell",
  },
  Py = {
    color = "#ffbc03",
    extension = { "py", "pyi" },
    file = { "py.typed" },
    filetype = { "python", "python2" },
    icon = "seti-python",
  },
  PyGen = {
    color = "#ffe291",
    extension = { "pyc", "pyd", "pyo" },
    icon = "seti-python",
  },
  Query = {
    color = "#90a850",
    extension = { "query" },
    icon = "fae-tree",
  },
  R = {
    color = "#2266ba",
    extension = { "r", "R" },
    file = { "R", "r" },
    filetype = { "r" },
    icon = "md-language_r",
  },
  RaspberryPiOS = {
    color = "#be1848",
    icon = "linux-raspberry_pi",
    os = { "raspberry_pi" },
  },
  RazorPage = {
    color = "#512bd4",
    extension = { "cshtml", "razor" },
    filetype = { "razor" },
    icon = "md-razor_double_edge",
  },
  ReScript = {
    color = "#cc3e44",
    extension = { "res" },
    filetype = { "rescript" },
    icon = "seti-rescript",
  },
  ReScriptInterface = {
    color = "#f55385",
    extension = { "resi" },
    icon = "seti-rescript",
  },
  Redhat = {
    color = "#EE0000",
    icon = "md-redhat",
    os = { "redhat" },
  },
  Rmd = {
    color = "#519aba",
    extension = { "rmd" },
    file = { "rmd" },
    filetype = { "rmarkdown" },
    icon = "seti-markdown",
  },
  RockyLinux = {
    color = "#0fb37d",
    icon = "linux-rocky_linux",
    os = { "rocky" },
  },
  Rproj = {
    color = "#358a5b",
    extension = { "rproj" },
    filetype = { "rproj" },
    icon = "md-vector_rectangle",
  },
  Rs = {
    color = "#dea584",
    extension = { "rlib", "rs" },
    filetype = { "rust" },
    icon = "dev-rust",
  },
  Rss = {
    color = "#FB9D3B",
    extension = { "rss" },
    icon = "seti-xml",
  },
  Ruby = {
    color = "#701516",
    extension = { "config.ru", "gemspec", "rake", "rb" },
    file = { "gemfile$", "rakefile" },
    filetype = { "gemfile" },
    icon = "dev-ruby_rough",
  },
  Sabayon = {
    color = "#c6c6c6",
    icon = "linux-sabayon",
    os = { "sabayon" },
  },
  Sass = {
    color = "#f55385",
    extension = { "sass", "scss" },
    filetype = { "sass", "scss" },
    icon = "seti-sass",
  },
  Scala = {
    color = "#cc3e44",
    extension = { "scala", "sbt" },
    filetype = { "scala" },
    icon = "dev-scala",
  },
  Scheme = {
    color = "#eeeeee",
    extension = { "scm" },
    filetype = { "scheme" },
    icon = "md-lambda",
  },
  SettingsJson = {
    color = "#854CC7",
    file = { ".settings.json" },
    icon = "dev-visualstudio",
  },
  Sh = {
    color = "#4d5a5e",
    extension = { "awk", "csh", "fish", "ksh", "sh" },
    filetype = { "awk", "csh", "fish", "sh" },
    icon = "dev-terminal",
  },
  Slackware = {
    color = "#475fa9",
    icon = "linux-slackware",
    os = { "slackware" },
  },
  Slim = {
    color = "#e34c26",
    extension = { "slim" },
    filetype = { "slim" },
    icon = "seti-html",
  },
  Sln = {
    color = "#854CC7",
    extension = { "sln" },
    icon = "dev-visualstudio",
  },
  Sml = {
    color = "#e37933",
    extension = { "sig", "sml" },
    filetype = { "sml" },
    icon = "λ",
  },
  Solidity = {
    color = "#519aba",
    extension = { "sol" },
    filetype = { "solidity" },
    icon = "seti-ethereum",
  },
  Solus = {
    color = "#4b5163",
    icon = "linux-solus",
    os = { "solus" },
  },
  Styl = {
    color = "#8dc149",
    extension = { "styl" },
    filetype = { "styl" },
    icon = "seti-stylus",
  },
  Suo = {
    color = "#854CC7",
    extension = { "suo", "sublime" },
    filetype = { "suo", "sublime" },
    icon = "dev-visualstudio",
  },
  Svelte = {
    color = "#ff3e00",
    extension = { "svelte" },
    file = { "svelte.config.js" },
    filetype = { "svelte" },
    icon = "seti-svelte",
  },
  Svg = {
    color = "#FFB13B",
    extension = { "svg" },
    filetype = { "svg" },
    icon = "md-svg",
  },
  Swift = {
    color = "#e37933",
    extension = { "swift" },
    filetype = { "swift" },
    icon = "dev-swift",
  },
  SystemVerilog = {
    color = "#019833",
    extension = { "svh", "sv" },
    filetype = { "systemverilog" },
    icon = "md-memory",
  },
  TFVars = {
    color = "#5F43E9",
    extension = { "tfvars" },
    icon = "fa-file",
  },
  TSConfig = {
    color = "#519aba",
    file = { "tsconfig.json" },
    icon = "seti-tsconfig",
  },
  TailwindConfig = {
    color = "#20c2e3",
    file = { "tailwind.config.js", "tailwind.config.mjs", "tailwind.config.ts" },
    icon = "md-tailwind",
  },
  Tcl = {
    color = "#1e5cb3",
    extension = { "tbc", "tcl" },
    filetype = { "tcl" },
    icon = "md-feather",
  },
  Templ = {
    color = "#dbbd30",
    extension = { "templ" },
    filetype = { "template" },
    icon = "cod-code",
  },
  Terminal = {
    color = "#31B53E",
    extension = { "terminal" },
    icon = "oct-terminal",
  },
  Terraform = {
    color = "#5F43E9",
    extension = { "tf" },
    filetype = { "terraform" },
    icon = "seti-terraform",
  },
  TestJs = {
    color = "#cbcb41",
    extension = { "spec.js", "test.js" },
    icon = "oct-beaker",
  },
  TestTs = {
    color = "#519aba",
    extension = { "spec.ts", "test.ts" },
    icon = "oct-beaker",
  },
  Tex = {
    color = "#3D6117",
    extension = { "tex" },
    filetype = { "tex" },
    icon = "md-text_shadow",
  },
  TextResource = {
    color = "#cbcb41",
    extension = { "tres" },
    icon = "dev-database",
  },
  TextScene = {
    color = "#a074c4",
    extension = { "tscn" },
    icon = "md-movie",
  },
  Toml = {
    color = "#9c4221",
    extension = { "toml" },
    filetype = { "toml" },
    icon = "custom-toml",
  },
  Tor = {
    color = "#519aba",
    extension = { "t" },
    icon = "dev-perl",
  },
  Ts = {
    color = "#519aba",
    extension = { "cts", "mts", "ts" },
    filetype = { "typescript" },
    icon = "seti-typescript",
  },
  Tsx = {
    color = "#1354bf",
    extension = { "tsx" },
    filetype = { "typescriptreact" },
    icon = "dev-react",
  },
  Twig = {
    color = "#8dc149",
    extension = { "twig" },
    icon = "seti-twig",
  },
  Txt = {
    color = "#89e051",
    extension = { "txt" },
    filetype = { "text" },
    icon = "md-file_document",
  },
  TypeScriptReactTest = {
    color = "#1354bf",
    extension = { "spec.tsx", "test.tsx" },
    icon = "oct-beaker",
  },
  Ubuntu = {
    color = "#dd4814",
    icon = "dev-ubuntu",
    os = { "ubuntu" },
  },
  VHDL = {
    color = "#019833",
    extension = { "vhdl", "vhd" },
    filetype = { "vhdl" },
    icon = "md-memory",
  },
  Vagrantfile = {
    color = "#1563FF",
    file = { "vagrantfile$" },
    filetype = { "vagrantfile" },
    icon = "fa-linode",
  },
  Vala = {
    color = "#7239b3",
    extension = { "vala" },
    filetype = { "vala" },
    icon = "seti-vala",
  },
  Verilog = {
    color = "#019833",
    extension = { "v", "vh" },
    filetype = { "verilog" },
    icon = "md-memory",
  },
  Vim = {
    color = "#019833",
    extension = { "vim" },
    file = { ".gvimrc", ".vimrc", "_gvimrc", "_vimrc" },
    filetype = { "vim" },
    icon = "custom-vim",
  },
  Vlang = {
    color = "#5d87bf",
    extension = { "vsh" },
    icon = "custom-v_lang",
  },
  Void = {
    color = "#295340",
    icon = "linux-void",
    os = { "void" },
  },
  Vue = {
    color = "#8dc149",
    extension = { "vue" },
    filetype = { "vue" },
    icon = "seti-vue",
  },
  Wasm = {
    color = "#5c4cdb",
    extension = { "wasm" },
    icon = "seti-wasm",
  },
  Webmanifest = {
    color = "#f1e05a",
    extension = { "webmanifest" },
    icon = "seti-less",
  },
  Webpack = {
    color = "#519aba",
    extension = { "webpack" },
    file = { "webpack" },
    icon = "md-webpack",
  },
  Windows = {
    color = "#00A4EF",
    icon = "fa-windows",
    os = { "windows" },
  },
  Word = {
    color = "#185abd",
    extension = { "doc", "docx" },
    icon = "md-file_word",
  },
  Xaml = {
    color = "#512bd4",
    extension = { "xaml" },
    icon = "md-language_xaml",
  },
  XcPlayground = {
    color = "#e37933",
    extension = { "xcplayground" },
    icon = "dev-swift",
  },
  Xml = {
    color = "#e37933",
    extension = { "xml" },
    filetype = { "xml" },
    icon = "md-xml",
  },
  Xul = {
    color = "#e37933",
    extension = { "xul" },
    icon = "dev-firefox",
  },
  Yaml = {
    color = "#6d8086",
    extension = { "yml", "yaml" },
    filetype = { "yaml" },
    icon = "seti-config",
  },
  Zig = {
    color = "#f69a1b",
    extension = { "zig" },
    file = { "build.zig.zon" },
    filetype = { "zig" },
    icon = "seti-zig",
  },
  Zorin = {
    color = "#14a1e8",
    icon = "linux-zorin",
    os = { "zorin" },
  },
  Zsh = {
    color = "#89e051",
    extension = { "zsh" },
    filetype = { "zsh" },
    icon = "dev-terminal",
  },
  ZshConfig = {
    color = "#89e051",
    file = { ".zshenv", ".zprofile", ".zshrc" },
    icon = "seti-config",
  },
}
