local icons_by_filename = {
  ["build.gradle"] = {
    icon = "",
    color = "#005f87",
    cterm_color = "24",
    name = "GradleBuildScript",
  },
  ["settings.gradle"] = {
    icon = "",
    color = "#005f87",
    cterm_color = "24",
    name = "GradleSettings",
  },
  [".babelrc"] = {
    icon = "",
    color = "#666620",
    cterm_color = "58",
    name = "Babelrc",
  },
  [".bash_profile"] = {
    icon = "",
    color = "#447028",
    cterm_color = "22",
    name = "BashProfile",
  },
  [".bashrc"] = {
    icon = "",
    color = "#447028",
    cterm_color = "22",
    name = "Bashrc",
  },
  [".dockerignore"] = {
    icon = "󰡨",
    color = "#2e5f99",
    cterm_color = "25",
    name = "Dockerfile",
  },
  [".ds_store"] = {
    icon = "",
    color = "#41535b",
    cterm_color = "239",
    name = "DsStore",
  },
  [".editorconfig"] = {
    icon = "",
    color = "#333030",
    cterm_color = "236",
    name = "EditorConfig",
  },
  [".env"] = {
    icon = "",
    color = "#32310d",
    cterm_color = "236",
    name = "Env",
  },
  [".eslintrc"] = {
    icon = "",
    color = "#4b32c3",
    cterm_color = "56",
    name = "Eslintrc",
  },
  [".eslintignore"] = {
    icon = "",
    color = "#4b32c3",
    cterm_color = "56",
    name = "EslintIgnore",
  },
  [".gitattributes"] = {
    icon = "",
    color = "#b83a1d",
    cterm_color = "160",
    name = "GitAttributes",
  },
  [".gitconfig"] = {
    icon = "",
    color = "#b83a1d",
    cterm_color = "160",
    name = "GitConfig",
  },
  [".gitignore"] = {
    icon = "",
    color = "#b83a1d",
    cterm_color = "160",
    name = "GitIgnore",
  },
  [".gitlab-ci.yml"] = {
    icon = "",
    color = "#aa321f",
    cterm_color = "124",
    name = "GitlabCI",
  },
  [".gitmodules"] = {
    icon = "",
    color = "#b83a1d",
    cterm_color = "160",
    name = "GitModules",
  },
  [".gtkrc-2.0"] = {
    icon = "",
    color = "#333333",
    cterm_color = "236",
    name = "GTK",
  },
  [".gvimrc"] = {
    icon = "",
    color = "#017226",
    cterm_color = "22",
    name = "Gvimrc",
  },
  [".luaurc"] = {
    icon = "",
    color = "#007abf",
    cterm_color = "32",
    name = "Luaurc",
  },
  [".mailmap"] = {
    icon = "󰊢",
    color = "#41535b",
    cterm_color = "239",
    name = "Mailmap",
  },
  [".npmignore"] = {
    icon = "",
    color = "#ae1d38",
    cterm_color = "161",
    name = "NPMIgnore",
  },
  [".npmrc"] = {
    icon = "",
    color = "#ae1d38",
    cterm_color = "161",
    name = "NPMrc",
  },
  [".prettierrc"] = {
    icon = "",
    color = "#3264b7",
    cterm_color = "25",
    name = "PrettierConfig",
  },
  [".settings.json"] = {
    icon = "",
    color = "#643995",
    cterm_color = "91",
    name = "SettingsJson",
  },
  [".SRCINFO"] = {
    icon = "󰣇",
    color = "#0b6f9e",
    cterm_color = "24",
    name = "SRCINFO",
  },
  [".vimrc"] = {
    icon = "",
    color = "#017226",
    cterm_color = "22",
    name = "Vimrc",
  },
  [".Xauthority"] = {
    icon = "",
    color = "#ac3a12",
    cterm_color = "124",
    name = "Xauthority",
  },
  [".xinitrc"] = {
    icon = "",
    color = "#ac3a12",
    cterm_color = "124",
    name = "XInitrc",
  },
  [".Xresources"] = {
    icon = "",
    color = "#ac3a12",
    cterm_color = "124",
    name = "Xresources",
  },
  [".xsession"] = {
    icon = "",
    color = "#ac3a12",
    cterm_color = "124",
    name = "Xsession",
  },
  [".zprofile"] = {
    icon = "",
    color = "#447028",
    cterm_color = "22",
    name = "Zshprofile",
  },
  [".zshenv"] = {
    icon = "",
    color = "#447028",
    cterm_color = "22",
    name = "Zshenv",
  },
  [".zshrc"] = {
    icon = "",
    color = "#447028",
    cterm_color = "22",
    name = "Zshrc",
  },
  ["_gvimrc"] = {
    icon = "",
    color = "#017226",
    cterm_color = "22",
    name = "Gvimrc",
  },
  ["_vimrc"] = {
    icon = "",
    color = "#017226",
    cterm_color = "22",
    name = "Vimrc",
  },
  ["R"] = {
    icon = "󰟔",
    color = "#1a4c8c",
    cterm_color = "25",
    name = "R",
  },
  ["avif"] = {
    icon = "",
    color = "#6b4d83",
    cterm_color = "96",
    name = "Avif",
  },
  ["brewfile"] = {
    icon = "",
    color = "#701516",
    cterm_color = "52",
    name = "Brewfile",
  },
  ["bspwmrc"] = {
    icon = "",
    color = "#2f2f2f",
    cterm_color = "236",
    name = "BSPWM",
  },
  ["build"] = {
    icon = "",
    color = "#447028",
    cterm_color = "22",
    name = "BazelBuild",
  },
  ["checkhealth"] = {
    icon = "󰓙",
    color = "#3a5a7e",
    cterm_color = "24",
    name = "Checkhealth",
  },
  ["cmakelists.txt"] = {
    icon = "",
    color = "#526064",
    cterm_color = "59",
    name = "CMakeLists",
  },
  ["commit_editmsg"] = {
    icon = "",
    color = "#b83a1d",
    cterm_color = "160",
    name = "GitCommit",
  },
  ["compose.yaml"] = {
    icon = "󰡨",
    color = "#2e5f99",
    cterm_color = "25",
    name = "Dockerfile",
  },
  ["compose.yml"] = {
    icon = "󰡨",
    color = "#2e5f99",
    cterm_color = "25",
    name = "Dockerfile",
  },
  ["config"] = {
    icon = "",
    color = "#526064",
    cterm_color = "59",
    name = "Config",
  },
  ["containerfile"] = {
    icon = "󰡨",
    color = "#2e5f99",
    cterm_color = "25",
    name = "Dockerfile",
  },
  ["copying"] = {
    icon = "",
    color = "#666620",
    cterm_color = "58",
    name = "License",
  },
  ["copying.lesser"] = {
    icon = "",
    color = "#666620",
    cterm_color = "58",
    name = "License",
  },
  ["docker-compose.yaml"] = {
    icon = "󰡨",
    color = "#2e5f99",
    cterm_color = "25",
    name = "Dockerfile",
  },
  ["docker-compose.yml"] = {
    icon = "󰡨",
    color = "#2e5f99",
    cterm_color = "25",
    name = "Dockerfile",
  },
  ["dockerfile"] = {
    icon = "󰡨",
    color = "#2e5f99",
    cterm_color = "25",
    name = "Dockerfile",
  },
  ["ext_typoscript_setup.txt"] = {
    icon = "",
    color = "#aa5a00",
    cterm_color = "130",
    name = "TypoScriptSetup",
  },
  ["favicon.ico"] = {
    icon = "",
    color = "#666620",
    cterm_color = "58",
    name = "Favicon",
  },
  ["fp-info-cache"] = {
    icon = "",
    color = "#333333",
    cterm_color = "236",
    name = "KiCadCache",
  },
  ["fp-lib-table"] = {
    icon = "",
    color = "#333333",
    cterm_color = "236",
    name = "KiCadFootprintTable",
  },
  ["FreeCAD.conf"] = {
    icon = "",
    color = "#cb0d0d",
    cterm_color = "160",
    name = "FreeCADConfig",
  },
  ["gemfile$"] = {
    icon = "",
    color = "#701516",
    cterm_color = "52",
    name = "Gemfile",
  },
  ["gnumakefile"] = {
    icon = "",
    color = "#526064",
    cterm_color = "59",
    name = "Makefile",
  },
  ["gradlew"] = {
    icon = "",
    color = "#005f87",
    cterm_color = "24",
    name = "GradleWrapperScript",
  },
  ["gradle.properties"] = {
    icon = "",
    color = "#005f87",
    cterm_color = "24",
    name = "GradleProperties",
  },
  ["gradle-wrapper.properties"] = {
    icon = "",
    color = "#005f87",
    cterm_color = "24",
    name = "GradleWrapperProperties",
  },
  ["groovy"] = {
    icon = "",
    color = "#384e5d",
    cterm_color = "239",
    name = "Groovy",
  },
  ["gruntfile"] = {
    icon = "",
    color = "#975122",
    cterm_color = "130",
    name = "Gruntfile",
  },
  ["gtkrc"] = {
    icon = "",
    color = "#333333",
    cterm_color = "236",
    name = "GTK",
  },
  ["gulpfile"] = {
    icon = "",
    color = "#992e33",
    cterm_color = "88",
    name = "Gulpfile",
  },
  ["hyprland.conf"] = {
    icon = "",
    color = "#008082",
    cterm_color = "30",
    name = "Hyprland",
  },
  ["i3blocks.conf"] = {
    icon = "",
    color = "#2e2f30",
    cterm_color = "236",
    name = "i3",
  },
  ["i3status.conf"] = {
    icon = "",
    color = "#2e2f30",
    cterm_color = "236",
    name = "i3",
  },
  ["cantorrc"] = {
    icon = "",
    color = "#1573b6",
    cterm_color = "32",
    name = "Cantorrc",
  },
  ["kalgebrarc"] = {
    icon = "",
    color = "#1573b6",
    cterm_color = "32",
    name = "Kalgebrarc",
  },
  ["kdeglobals"] = {
    icon = "",
    color = "#1573b6",
    cterm_color = "32",
    name = "KDEglobals",
  },
  ["kdenlive-layoutsrc"] = {
    icon = "",
    color = "#425c79",
    cterm_color = "24",
    name = "KdenliveLayoutsrc",
  },
  ["kdenliverc"] = {
    icon = "",
    color = "#425c79",
    cterm_color = "24",
    name = "Kdenliverc",
  },
  ["kritadisplayrc"] = {
    icon = "",
    color = "#a12ea7",
    cterm_color = "127",
    name = "Kritadisplayrc",
  },
  ["kritarc"] = {
    icon = "",
    color = "#a12ea7",
    cterm_color = "127",
    name = "Kritarc",
  },
  ["license"] = {
    icon = "",
    color = "#686020",
    cterm_color = "58",
    name = "License",
  },
  ["lxde-rc.xml"] = {
    icon = "",
    color = "#606060",
    cterm_color = "59",
    name = "LXDEConfigFile",
  },
  ["lxqt.conf"] = {
    icon = "",
    color = "#016e9e",
    cterm_color = "24",
    name = "LXQtConfigFile",
  },
  ["makefile"] = {
    icon = "",
    color = "#526064",
    cterm_color = "59",
    name = "Makefile",
  },
  ["mix.lock"] = {
    icon = "",
    color = "#6b4d83",
    cterm_color = "96",
    name = "MixLock",
  },
  ["mpv.conf"] = {
    icon = "",
    color = "#3b1342",
    cterm_color = "53",
    name = "Mpv",
  },
  ["node_modules"] = {
    icon = "",
    color = "#ae1d38",
    cterm_color = "161",
    name = "NodeModules",
  },
  ["package.json"] = {
    icon = "",
    color = "#ae1d38",
    cterm_color = "161",
    name = "PackageJson",
  },
  ["package-lock.json"] = {
    icon = "",
    color = "#7a0d21",
    cterm_color = "52",
    name = "PackageLockJson",
  },
  ["PKGBUILD"] = {
    icon = "",
    color = "#0b6f9e",
    cterm_color = "24",
    name = "PKGBUILD",
  },
  ["platformio.ini"] = {
    icon = "",
    color = "#a4571d",
    cterm_color = "130",
    name = "Platformio",
  },
  ["pom.xml"] = {
    icon = "",
    color = "#7a0d21",
    cterm_color = "52",
    name = "Maven",
  },
  ["procfile"] = {
    icon = "",
    color = "#6b4d83",
    cterm_color = "96",
    name = "Procfile",
  },
  ["PrusaSlicer.ini"] = {
    icon = "",
    color = "#9d4717",
    cterm_color = "130",
    name = "PrusaSlicer",
  },
  ["PrusaSlicerGcodeViewer.ini"] = {
    icon = "",
    color = "#9d4717",
    cterm_color = "130",
    name = "PrusaSlicer",
  },
  ["py.typed"] = {
    icon = "",
    color = "#805e02",
    cterm_color = "94",
    name = "Py.typed",
  },
  ["QtProject.conf"] = {
    icon = "",
    color = "#2b8937",
    cterm_color = "28",
    name = "Qt",
  },
  ["r"] = {
    icon = "󰟔",
    color = "#1a4c8c",
    cterm_color = "25",
    name = "R",
  },
  ["rakefile"] = {
    icon = "",
    color = "#701516",
    cterm_color = "52",
    name = "Rakefile",
  },
  ["rmd"] = {
    icon = "",
    color = "#36677c",
    cterm_color = "24",
    name = "Rmd",
  },
  ["svelte.config.js"] = {
    icon = "",
    color = "#bf2e00",
    cterm_color = "160",
    name = "SvelteConfig",
  },
  ["sxhkdrc"] = {
    icon = "",
    color = "#2f2f2f",
    cterm_color = "236",
    name = "BSPWM",
  },
  ["sym-lib-table"] = {
    icon = "",
    color = "#333333",
    cterm_color = "236",
    name = "KiCadSymbolTable",
  },
  ["tailwind.config.js"] = {
    icon = "󱏿",
    color = "#158197",
    cterm_color = "31",
    name = "TailwindConfig",
  },
  ["tailwind.config.mjs"] = {
    icon = "󱏿",
    color = "#158197",
    cterm_color = "31",
    name = "TailwindConfig",
  },
  ["tailwind.config.ts"] = {
    icon = "󱏿",
    color = "#158197",
    cterm_color = "31",
    name = "TailwindConfig",
  },
  ["tmux.conf"] = {
    icon = "",
    color = "#0f8c13",
    cterm_color = "28",
    name = "Tmux",
  },
  ["tmux.conf.local"] = {
    icon = "",
    color = "#0f8c13",
    cterm_color = "28",
    name = "Tmux",
  },
  ["tsconfig.json"] = {
    icon = "",
    color = "#36677c",
    cterm_color = "24",
    name = "TSConfig",
  },
  ["unlicense"] = {
    icon = "",
    color = "#686020",
    cterm_color = "58",
    name = "License",
  },
  ["vagrantfile$"] = {
    icon = "",
    color = "#104abf",
    cterm_color = "26",
    name = "Vagrantfile",
  },
  ["vlcrc"] = {
    icon = "󰕼",
    color = "#9f5100",
    cterm_color = "130",
    name = "VLC",
  },
  ["webpack"] = {
    icon = "󰜫",
    color = "#36677c",
    cterm_color = "24",
    name = "Webpack",
  },
  ["weston.ini"] = {
    icon = "",
    color = "#805e00",
    cterm_color = "94",
    name = "Weston",
  },
  ["workspace"] = {
    icon = "",
    color = "#447028",
    cterm_color = "22",
    name = "BazelWorkspace",
  },
  ["xmobarrc"] = {
    icon = "",
    color = "#a9333e",
    cterm_color = "131",
    name = "xmonad",
  },
  ["xmobarrc.hs"] = {
    icon = "",
    color = "#a9333e",
    cterm_color = "131",
    name = "xmonad",
  },
  ["xmonad.hs"] = {
    icon = "",
    color = "#a9333e",
    cterm_color = "131",
    name = "xmonad",
  },
  ["xorg.conf"] = {
    icon = "",
    color = "#ac3a12",
    cterm_color = "124",
    name = "XorgConf",
  },
  ["xsettingsd.conf"] = {
    icon = "",
    color = "#ac3a12",
    cterm_color = "124",
    name = "XSettingsdConf",
  },
  ["build.zig.zon"] = {
    icon = "",
    color = "#7b4d0e",
    cterm_color = "94",
    name = "ZigObjectNotation",
  },
}

local icons_by_file_extension = {
  ["3gp"] = {
    icon = "",
    color = "#7e4c10",
    cterm_color = "94",
    name = "3gp",
  },
  ["3mf"] = {
    icon = "󰆧",
    color = "#5b5b5b",
    cterm_color = "240",
    name = "3DObjectFile",
  },
  ["7z"] = {
    icon = "",
    color = "#76520c",
    cterm_color = "94",
    name = "7z",
  },
  ["a"] = {
    icon = "",
    color = "#494a47",
    cterm_color = "239",
    name = "StaticLibraryArchive",
  },
  ["aac"] = {
    icon = "",
    color = "#0075aa",
    cterm_color = "24",
    name = "AdvancedAudioCoding",
  },
  ["aif"] = {
    icon = "",
    color = "#0075aa",
    cterm_color = "24",
    name = "AudioInterchangeFileFormat",
  },
  ["aiff"] = {
    icon = "",
    color = "#0075aa",
    cterm_color = "24",
    name = "AudioInterchangeFileFormat",
  },
  ["ape"] = {
    icon = "",
    color = "#0075aa",
    cterm_color = "24",
    name = "MonkeysAudio",
  },
  ["ai"] = {
    icon = "",
    color = "#666620",
    cterm_color = "58",
    name = "Ai",
  },
  ["android"] = {
    icon = "",
    color = "#277e3e",
    cterm_color = "29",
    name = "Android",
  },
  ["apk"] = {
    icon = "",
    color = "#277e3e",
    cterm_color = "29",
    name = "apk",
  },
  ["app"] = {
    icon = "",
    color = "#9F0500",
    cterm_color = "124",
    name = "App",
  },
  ["applescript"] = {
    icon = "",
    color = "#526064",
    cterm_color = "59",
    name = "AppleScript",
  },
  ["asc"] = {
    icon = "󰦝",
    color = "#41525f",
    cterm_color = "239",
    name = "Asc",
  },
  ["ass"] = {
    icon = "󰨖",
    color = "#805c0a",
    cterm_color = "94",
    name = "Ass",
  },
  ["astro"] = {
    icon = "",
    color = "#aa2f4d",
    cterm_color = "125",
    name = "Astro",
  },
  ["awk"] = {
    icon = "",
    color = "#3a4446",
    cterm_color = "238",
    name = "Awk",
  },
  ["azcli"] = {
    icon = "",
    color = "#005a9f",
    cterm_color = "25",
    name = "AzureCli",
  },
  ["bak"] = {
    icon = "󰁯",
    color = "#526064",
    cterm_color = "59",
    name = "Backup",
  },
  ["bash"] = {
    icon = "",
    color = "#447028",
    cterm_color = "22",
    name = "Bash",
  },
  ["bat"] = {
    icon = "",
    color = "#40500f",
    cterm_color = "58",
    name = "Bat",
  },
  ["bazel"] = {
    icon = "",
    color = "#447028",
    cterm_color = "22",
    name = "Bazel",
  },
  ["bib"] = {
    icon = "󱉟",
    color = "#666620",
    cterm_color = "58",
    name = "BibTeX",
  },
  ["bin"] = {
    icon = "",
    color = "#9F0500",
    cterm_color = "124",
    name = "Bin",
  },
  ["blade.php"] = {
    icon = "",
    color = "#a0372b",
    cterm_color = "124",
    name = "Blade",
  },
  ["blend"] = {
    icon = "󰂫",
    color = "#9c4f00",
    cterm_color = "130",
    name = "Blender",
  },
  ["bmp"] = {
    icon = "",
    color = "#6b4d83",
    cterm_color = "96",
    name = "Bmp",
  },
  ["blp"] = {
    icon = "󰺾",
    color = "#3a6497",
    cterm_color = "25",
    name = "Blueprint",
  },
  ["brep"] = {
    icon = "󰻫",
    color = "#576342",
    cterm_color = "58",
    name = "BoundaryRepresentation",
  },
  ["bz"] = {
    icon = "",
    color = "#76520c",
    cterm_color = "94",
    name = "Bz",
  },
  ["bz2"] = {
    icon = "",
    color = "#76520c",
    cterm_color = "94",
    name = "Bz2",
  },
  ["bz3"] = {
    icon = "",
    color = "#76520c",
    cterm_color = "94",
    name = "Bz3",
  },
  ["bzl"] = {
    icon = "",
    color = "#447028",
    cterm_color = "22",
    name = "Bzl",
  },
  ["c"] = {
    icon = "",
    color = "#3b69aa",
    cterm_color = "25",
    name = "C",
  },
  ["c++"] = {
    icon = "",
    color = "#a23253",
    cterm_color = "125",
    name = "CPlusPlus",
  },
  ["cache"] = {
    icon = "",
    color = "#333333",
    cterm_color = "236",
    name = "Cache",
  },
  ["cast"] = {
    icon = "",
    color = "#7e4c10",
    cterm_color = "94",
    name = "Asciinema",
  },
  ["cbl"] = {
    icon = "⚙",
    color = "#005ca5",
    cterm_color = "25",
    name = "Cobol",
  },
  ["cc"] = {
    icon = "",
    color = "#a23253",
    cterm_color = "125",
    name = "CPlusPlus",
  },
  ["ccm"] = {
    icon = "",
    color = "#a23253",
    cterm_color = "125",
    name = "CPlusPlusModule",
  },
  ["cfg"] = {
    icon = "",
    color = "#526064",
    cterm_color = "59",
    name = "Configuration",
  },
  ["cjs"] = {
    icon = "",
    color = "#666620",
    cterm_color = "58",
    name = "Cjs",
  },
  ["clj"] = {
    icon = "",
    color = "#466024",
    cterm_color = "22",
    name = "Clojure",
  },
  ["cljc"] = {
    icon = "",
    color = "#466024",
    cterm_color = "22",
    name = "ClojureC",
  },
  ["cljs"] = {
    icon = "",
    color = "#36677c",
    cterm_color = "24",
    name = "ClojureJS",
  },
  ["cljd"] = {
    icon = "",
    color = "#36677c",
    cterm_color = "24",
    name = "ClojureDart",
  },
  ["cmake"] = {
    icon = "",
    color = "#526064",
    cterm_color = "59",
    name = "CMake",
  },
  ["cob"] = {
    icon = "⚙",
    color = "#005ca5",
    cterm_color = "25",
    name = "Cobol",
  },
  ["cobol"] = {
    icon = "⚙",
    color = "#005ca5",
    cterm_color = "25",
    name = "Cobol",
  },
  ["coffee"] = {
    icon = "",
    color = "#666620",
    cterm_color = "58",
    name = "Coffee",
  },
  ["conf"] = {
    icon = "",
    color = "#526064",
    cterm_color = "59",
    name = "Conf",
  },
  ["config.ru"] = {
    icon = "",
    color = "#701516",
    cterm_color = "52",
    name = "ConfigRu",
  },
  ["cp"] = {
    icon = "",
    color = "#36677c",
    cterm_color = "24",
    name = "Cp",
  },
  ["cpp"] = {
    icon = "",
    color = "#36677c",
    cterm_color = "24",
    name = "Cpp",
  },
  ["cppm"] = {
    icon = "",
    color = "#36677c",
    cterm_color = "24",
    name = "Cppm",
  },
  ["cpy"] = {
    icon = "⚙",
    color = "#005ca5",
    cterm_color = "25",
    name = "Cobol",
  },
  ["cr"] = {
    icon = "",
    color = "#434343",
    cterm_color = "238",
    name = "Crystal",
  },
  ["crdownload"] = {
    icon = "",
    color = "#226654",
    cterm_color = "23",
    name = "Crdownload",
  },
  ["cs"] = {
    icon = "󰌛",
    color = "#434d04",
    cterm_color = "58",
    name = "Cs",
  },
  ["csh"] = {
    icon = "",
    color = "#3a4446",
    cterm_color = "238",
    name = "Csh",
  },
  ["cshtml"] = {
    icon = "󱦗",
    color = "#512bd4",
    cterm_color = "56",
    name = "RazorPage",
  },
  ["cson"] = {
    icon = "",
    color = "#666620",
    cterm_color = "58",
    name = "Cson",
  },
  ["csproj"] = {
    icon = "󰪮",
    color = "#512bd4",
    cterm_color = "56",
    name = "CSharpProject",
  },
  ["css"] = {
    icon = "",
    color = "#2c6ea3",
    cterm_color = "24",
    name = "Css",
  },
  ["csv"] = {
    icon = "",
    color = "#447028",
    cterm_color = "22",
    name = "Csv",
  },
  ["cts"] = {
    icon = "",
    color = "#36677c",
    cterm_color = "24",
    name = "Cts",
  },
  ["cu"] = {
    icon = "",
    color = "#447028",
    cterm_color = "22",
    name = "cuda",
  },
  ["cue"] = {
    icon = "󰲹",
    color = "#764a57",
    cterm_color = "95",
    name = "Cue",
  },
  ["cuh"] = {
    icon = "",
    color = "#6b4d83",
    cterm_color = "96",
    name = "cudah",
  },
  ["cxx"] = {
    icon = "",
    color = "#36677c",
    cterm_color = "24",
    name = "Cxx",
  },
  ["cxxm"] = {
    icon = "",
    color = "#36677c",
    cterm_color = "24",
    name = "Cxxm",
  },
  ["d"] = {
    icon = "",
    color = "#325a13",
    cterm_color = "22",
    name = "D",
  },
  ["dart"] = {
    icon = "",
    color = "#03589C",
    cterm_color = "25",
    name = "Dart",
  },
  ["db"] = {
    icon = "",
    color = "#494848",
    cterm_color = "238",
    name = "Db",
  },
  ["dconf"] = {
    icon = "",
    color = "#333333",
    cterm_color = "236",
    name = "Dconf",
  },
  ["desktop"] = {
    icon = "",
    color = "#563d7c",
    cterm_color = "54",
    name = "DesktopEntry",
  },
  ["diff"] = {
    icon = "",
    color = "#41535b",
    cterm_color = "239",
    name = "Diff",
  },
  ["dll"] = {
    icon = "",
    color = "#4d2c0b",
    cterm_color = "52",
    name = "Dll",
  },
  ["doc"] = {
    icon = "󰈬",
    color = "#185abd",
    cterm_color = "26",
    name = "Doc",
  },
  ["Dockerfile"] = {
    icon = "󰡨",
    color = "#2e5f99",
    cterm_color = "25",
    name = "Dockerfile",
  },
  ["docx"] = {
    icon = "󰈬",
    color = "#185abd",
    cterm_color = "26",
    name = "Docx",
  },
  ["dot"] = {
    icon = "󱁉",
    color = "#244a6a",
    cterm_color = "24",
    name = "Dot",
  },
  ["download"] = {
    icon = "",
    color = "#226654",
    cterm_color = "23",
    name = "Download",
  },
  ["drl"] = {
    icon = "",
    color = "#553a3a",
    cterm_color = "238",
    name = "Drools",
  },
  ["dropbox"] = {
    icon = "",
    color = "#0049be",
    cterm_color = "26",
    name = "Dropbox",
  },
  ["dump"] = {
    icon = "",
    color = "#494848",
    cterm_color = "238",
    name = "Dump",
  },
  ["dwg"] = {
    icon = "󰻫",
    color = "#576342",
    cterm_color = "58",
    name = "AutoCADDwg",
  },
  ["dxf"] = {
    icon = "󰻫",
    color = "#576342",
    cterm_color = "58",
    name = "AutoCADDxf",
  },
  ["ebook"] = {
    icon = "",
    color = "#755836",
    cterm_color = "94",
    name = "Ebook",
  },
  ["edn"] = {
    icon = "",
    color = "#36677c",
    cterm_color = "24",
    name = "Edn",
  },
  ["eex"] = {
    icon = "",
    color = "#6b4d83",
    cterm_color = "96",
    name = "Eex",
  },
  ["ejs"] = {
    icon = "",
    color = "#666620",
    cterm_color = "58",
    name = "Ejs",
  },
  ["elf"] = {
    icon = "",
    color = "#9F0500",
    cterm_color = "124",
    name = "Elf",
  },
  ["el"] = {
    icon = "",
    color = "#61568e",
    cterm_color = "60",
    name = "Elisp",
  },
  ["elc"] = {
    icon = "",
    color = "#61568e",
    cterm_color = "60",
    name = "Elisp",
  },
  ["elm"] = {
    icon = "",
    color = "#36677c",
    cterm_color = "24",
    name = "Elm",
  },
  ["eln"] = {
    icon = "",
    color = "#61568e",
    cterm_color = "60",
    name = "Elisp",
  },
  ["env"] = {
    icon = "",
    color = "#32310d",
    cterm_color = "236",
    name = "Env",
  },
  ["eot"] = {
    icon = "",
    color = "#2f2f2f",
    cterm_color = "236",
    name = "EmbeddedOpenTypeFont",
  },
  ["epp"] = {
    icon = "",
    color = "#80530d",
    cterm_color = "94",
    name = "Epp",
  },
  ["epub"] = {
    icon = "",
    color = "#755836",
    cterm_color = "94",
    name = "Epub",
  },
  ["erb"] = {
    icon = "",
    color = "#701516",
    cterm_color = "52",
    name = "Erb",
  },
  ["erl"] = {
    icon = "",
    color = "#8a2b72",
    cterm_color = "89",
    name = "Erl",
  },
  ["ex"] = {
    icon = "",
    color = "#6b4d83",
    cterm_color = "96",
    name = "Ex",
  },
  ["exe"] = {
    icon = "",
    color = "#9F0500",
    cterm_color = "124",
    name = "Exe",
  },
  ["exs"] = {
    icon = "",
    color = "#6b4d83",
    cterm_color = "96",
    name = "Exs",
  },
  ["f#"] = {
    icon = "",
    color = "#36677c",
    cterm_color = "24",
    name = "Fsharp",
  },
  ["f3d"] = {
    icon = "󰻫",
    color = "#576342",
    cterm_color = "58",
    name = "Fusion360",
  },
  ["f90"] = {
    icon = "󱈚",
    color = "#563b70",
    cterm_color = "53",
    name = "Fortran",
  },
  ["fbx"] = {
    icon = "󰆧",
    color = "#5b5b5b",
    cterm_color = "240",
    name = "3DObjectFile",
  },
  ["fcbak"] = {
    icon = "",
    color = "#cb0d0d",
    cterm_color = "160",
    name = "FreeCAD",
  },
  ["fcmacro"] = {
    icon = "",
    color = "#cb0d0d",
    cterm_color = "160",
    name = "FreeCAD",
  },
  ["fcmat"] = {
    icon = "",
    color = "#cb0d0d",
    cterm_color = "160",
    name = "FreeCAD",
  },
  ["fcparam"] = {
    icon = "",
    color = "#cb0d0d",
    cterm_color = "160",
    name = "FreeCAD",
  },
  ["fcscript"] = {
    icon = "",
    color = "#cb0d0d",
    cterm_color = "160",
    name = "FreeCAD",
  },
  ["fcstd"] = {
    icon = "",
    color = "#cb0d0d",
    cterm_color = "160",
    name = "FreeCAD",
  },
  ["fcstd1"] = {
    icon = "",
    color = "#cb0d0d",
    cterm_color = "160",
    name = "FreeCAD",
  },
  ["fctb"] = {
    icon = "",
    color = "#cb0d0d",
    cterm_color = "160",
    name = "FreeCAD",
  },
  ["fctl"] = {
    icon = "",
    color = "#cb0d0d",
    cterm_color = "160",
    name = "FreeCAD",
  },
  ["fdmdownload"] = {
    icon = "",
    color = "#226654",
    cterm_color = "23",
    name = "Fdmdownload",
  },
  ["flac"] = {
    icon = "",
    color = "#005880",
    cterm_color = "24",
    name = "FreeLosslessAudioCodec",
  },
  ["flc"] = {
    icon = "",
    color = "#2f2f2f",
    cterm_color = "236",
    name = "FIGletFontControl",
  },
  ["flf"] = {
    icon = "",
    color = "#2f2f2f",
    cterm_color = "236",
    name = "FIGletFontFormat",
  },
  ["fnl"] = {
    icon = "",
    color = "#33312b",
    cterm_color = "236",
    name = "Fennel",
  },
  ["fish"] = {
    icon = "",
    color = "#3a4446",
    cterm_color = "238",
    name = "Fish",
  },
  ["fs"] = {
    icon = "",
    color = "#36677c",
    cterm_color = "24",
    name = "Fs",
  },
  ["fsi"] = {
    icon = "",
    color = "#36677c",
    cterm_color = "24",
    name = "Fsi",
  },
  ["fsscript"] = {
    icon = "",
    color = "#36677c",
    cterm_color = "24",
    name = "Fsscript",
  },
  ["fsx"] = {
    icon = "",
    color = "#36677c",
    cterm_color = "24",
    name = "Fsx",
  },
  ["gcode"] = {
    icon = "󰐫",
    color = "#0f5582",
    cterm_color = "24",
    name = "GCode",
  },
  ["gd"] = {
    icon = "",
    color = "#526064",
    cterm_color = "59",
    name = "GDScript",
  },
  ["gemspec"] = {
    icon = "",
    color = "#701516",
    cterm_color = "52",
    name = "Gemspec",
  },
  ["gif"] = {
    icon = "",
    color = "#6b4d83",
    cterm_color = "96",
    name = "Gif",
  },
  ["git"] = {
    icon = "",
    color = "#b5391e",
    cterm_color = "160",
    name = "GitLogo",
  },
  ["glb"] = {
    icon = "",
    color = "#80581e",
    cterm_color = "94",
    name = "BinaryGLTF",
  },
  ["gnumakefile"] = {
    icon = "",
    color = "#526064",
    cterm_color = "59",
    name = "Makefile",
  },
  ["go"] = {
    icon = "",
    color = "#36677c",
    cterm_color = "24",
    name = "Go",
  },
  ["godot"] = {
    icon = "",
    color = "#526064",
    cterm_color = "59",
    name = "GodotProject",
  },
  ["gql"] = {
    icon = "",
    color = "#ac2880",
    cterm_color = "126",
    name = "GraphQL",
  },
  ["graphql"] = {
    icon = "",
    color = "#ac2880",
    cterm_color = "126",
    name = "GraphQL",
  },
  ["gresource"] = {
    icon = "",
    color = "#333333",
    cterm_color = "236",
    name = "GTK",
  },
  ["gv"] = {
    icon = "󱁉",
    color = "#244a6a",
    cterm_color = "24",
    name = "Gv",
  },
  ["gz"] = {
    icon = "",
    color = "#76520c",
    cterm_color = "94",
    name = "Gz",
  },
  ["h"] = {
    icon = "",
    color = "#6b4d83",
    cterm_color = "96",
    name = "H",
  },
  ["haml"] = {
    icon = "",
    color = "#2f2f2d",
    cterm_color = "236",
    name = "Haml",
  },
  ["hx"] = {
    icon = "",
    color = "#9c5715",
    cterm_color = "130",
    name = "Haxe",
  },
  ["hbs"] = {
    icon = "",
    color = "#a04f1d",
    cterm_color = "130",
    name = "Hbs",
  },
  ["hex"] = {
    icon = "",
    color = "#224abf",
    cterm_color = "26",
    name = "Hexadecimal",
  },
  ["heex"] = {
    icon = "",
    color = "#6b4d83",
    cterm_color = "96",
    name = "Heex",
  },
  ["hh"] = {
    icon = "",
    color = "#6b4d83",
    cterm_color = "96",
    name = "Hh",
  },
  ["hpp"] = {
    icon = "",
    color = "#6b4d83",
    cterm_color = "96",
    name = "Hpp",
  },
  ["hrl"] = {
    icon = "",
    color = "#8a2b72",
    cterm_color = "89",
    name = "Hrl",
  },
  ["hs"] = {
    icon = "",
    color = "#6b4d83",
    cterm_color = "96",
    name = "Hs",
  },
  ["htm"] = {
    icon = "",
    color = "#aa391c",
    cterm_color = "124",
    name = "Htm",
  },
  ["html"] = {
    icon = "",
    color = "#ab3a1c",
    cterm_color = "124",
    name = "Html",
  },
  ["huff"] = {
    icon = "󰡘",
    color = "#4242c7",
    cterm_color = "56",
    name = "Huff",
  },
  ["hurl"] = {
    icon = "",
    color = "#bf0266",
    cterm_color = "125",
    name = "Hurl",
  },
  ["hxx"] = {
    icon = "",
    color = "#6b4d83",
    cterm_color = "96",
    name = "Hxx",
  },
  ["ixx"] = {
    icon = "",
    color = "#36677c",
    cterm_color = "24",
    name = "Ixx",
  },
  ["ico"] = {
    icon = "",
    color = "#666620",
    cterm_color = "58",
    name = "Ico",
  },
  ["ical"] = {
    icon = "",
    color = "#2B2e83",
    cterm_color = "18",
    name = "Ical",
  },
  ["icalendar"] = {
    icon = "",
    color = "#2B2e83",
    cterm_color = "18",
    name = "Icalendar",
  },
  ["ics"] = {
    icon = "",
    color = "#2B2e83",
    cterm_color = "18",
    name = "Ics",
  },
  ["ifb"] = {
    icon = "",
    color = "#2B2e83",
    cterm_color = "18",
    name = "Ifb",
  },
  ["ifc"] = {
    icon = "󰻫",
    color = "#576342",
    cterm_color = "58",
    name = "Ifc",
  },
  ["ige"] = {
    icon = "󰻫",
    color = "#576342",
    cterm_color = "58",
    name = "Ige",
  },
  ["iges"] = {
    icon = "󰻫",
    color = "#576342",
    cterm_color = "58",
    name = "Iges",
  },
  ["igs"] = {
    icon = "󰻫",
    color = "#576342",
    cterm_color = "58",
    name = "Igs",
  },
  ["image"] = {
    icon = "",
    color = "#453f43",
    cterm_color = "238",
    name = "Image",
  },
  ["img"] = {
    icon = "",
    color = "#453f43",
    cterm_color = "238",
    name = "Img",
  },
  ["import"] = {
    icon = "",
    color = "#2f2f2f",
    cterm_color = "236",
    name = "ImportConfiguration",
  },
  ["info"] = {
    icon = "",
    color = "#333329",
    cterm_color = "236",
    name = "Info",
  },
  ["ini"] = {
    icon = "",
    color = "#526064",
    cterm_color = "59",
    name = "Ini",
  },
  ["ino"] = {
    icon = "",
    color = "#397981",
    cterm_color = "30",
    name = "Arduino",
  },
  ["iso"] = {
    icon = "",
    color = "#453f43",
    cterm_color = "238",
    name = "Iso",
  },
  ["ipynb"] = {
    icon = "",
    color = "#366b8a",
    cterm_color = "24",
    name = "Notebook",
  },
  ["java"] = {
    icon = "",
    color = "#992e33",
    cterm_color = "88",
    name = "Java",
  },
  ["jl"] = {
    icon = "",
    color = "#6c4b7c",
    cterm_color = "96",
    name = "Jl",
  },
  ["jwmrc"] = {
    icon = "",
    color = "#005a9a",
    cterm_color = "25",
    name = "JWM",
  },
  ["jpeg"] = {
    icon = "",
    color = "#6b4d83",
    cterm_color = "96",
    name = "Jpeg",
  },
  ["jpg"] = {
    icon = "",
    color = "#6b4d83",
    cterm_color = "96",
    name = "Jpg",
  },
  ["js"] = {
    icon = "",
    color = "#666620",
    cterm_color = "58",
    name = "Js",
  },
  ["json"] = {
    icon = "",
    color = "#666620",
    cterm_color = "58",
    name = "Json",
  },
  ["json5"] = {
    icon = "",
    color = "#666620",
    cterm_color = "58",
    name = "Json5",
  },
  ["jsonc"] = {
    icon = "",
    color = "#666620",
    cterm_color = "58",
    name = "Jsonc",
  },
  ["jsx"] = {
    icon = "",
    color = "#158197",
    cterm_color = "31",
    name = "Jsx",
  },
  ["jxl"] = {
    icon = "",
    color = "#6b4d83",
    cterm_color = "96",
    name = "JpegXl",
  },
  ["kbx"] = {
    icon = "󰯄",
    color = "#565856",
    cterm_color = "240",
    name = "Kbx",
  },
  ["kdb"] = {
    icon = "",
    color = "#3e7427",
    cterm_color = "28",
    name = "Kdb",
  },
  ["kdbx"] = {
    icon = "",
    color = "#3e7427",
    cterm_color = "28",
    name = "Kdbx",
  },
  ["kdenlive"] = {
    icon = "",
    color = "#425c79",
    cterm_color = "24",
    name = "Kdenlive",
  },
  ["kdenlivetitle"] = {
    icon = "",
    color = "#425c79",
    cterm_color = "24",
    name = "Kdenlive",
  },
  ["kicad_dru"] = {
    icon = "",
    color = "#333333",
    cterm_color = "236",
    name = "KiCad",
  },
  ["kicad_mod"] = {
    icon = "",
    color = "#333333",
    cterm_color = "236",
    name = "KiCad",
  },
  ["kicad_pcb"] = {
    icon = "",
    color = "#333333",
    cterm_color = "236",
    name = "KiCad",
  },
  ["kicad_prl"] = {
    icon = "",
    color = "#333333",
    cterm_color = "236",
    name = "KiCad",
  },
  ["kicad_pro"] = {
    icon = "",
    color = "#333333",
    cterm_color = "236",
    name = "KiCad",
  },
  ["kicad_sch"] = {
    icon = "",
    color = "#333333",
    cterm_color = "236",
    name = "KiCad",
  },
  ["kicad_sym"] = {
    icon = "",
    color = "#333333",
    cterm_color = "236",
    name = "KiCad",
  },
  ["kicad_wks"] = {
    icon = "",
    color = "#333333",
    cterm_color = "236",
    name = "KiCad",
  },
  ["ko"] = {
    icon = "",
    color = "#494a47",
    cterm_color = "239",
    name = "LinuxKernelObject",
  },
  ["kpp"] = {
    icon = "",
    color = "#a12ea7",
    cterm_color = "127",
    name = "Krita",
  },
  ["kra"] = {
    icon = "",
    color = "#a12ea7",
    cterm_color = "127",
    name = "Krita",
  },
  ["krz"] = {
    icon = "",
    color = "#a12ea7",
    cterm_color = "127",
    name = "Krita",
  },
  ["ksh"] = {
    icon = "",
    color = "#3a4446",
    cterm_color = "238",
    name = "Ksh",
  },
  ["kt"] = {
    icon = "",
    color = "#5f3ebf",
    cterm_color = "92",
    name = "Kotlin",
  },
  ["kts"] = {
    icon = "",
    color = "#5f3ebf",
    cterm_color = "92",
    name = "KotlinScript",
  },
  ["lck"] = {
    icon = "",
    color = "#5e5e5e",
    cterm_color = "59",
    name = "Lock",
  },
  ["leex"] = {
    icon = "",
    color = "#6b4d83",
    cterm_color = "96",
    name = "Leex",
  },
  ["less"] = {
    icon = "",
    color = "#563d7c",
    cterm_color = "54",
    name = "Less",
  },
  ["lff"] = {
    icon = "",
    color = "#2f2f2f",
    cterm_color = "236",
    name = "LibrecadFontFile",
  },
  ["lhs"] = {
    icon = "",
    color = "#6b4d83",
    cterm_color = "96",
    name = "Lhs",
  },
  ["lib"] = {
    icon = "",
    color = "#4d2c0b",
    cterm_color = "52",
    name = "Lib",
  },
  ["license"] = {
    icon = "",
    color = "#666620",
    cterm_color = "58",
    name = "License",
  },
  ["liquid"] = {
    icon = "",
    color = "#4a6024",
    cterm_color = "58",
    name = "Liquid",
  },
  ["lock"] = {
    icon = "",
    color = "#5e5e5e",
    cterm_color = "59",
    name = "Lock",
  },
  ["log"] = {
    icon = "󰌱",
    color = "#4a4a4a",
    cterm_color = "239",
    name = "Log",
  },
  ["lrc"] = {
    icon = "󰨖",
    color = "#805c0a",
    cterm_color = "94",
    name = "Lrc",
  },
  ["lua"] = {
    icon = "",
    color = "#366b8a",
    cterm_color = "24",
    name = "Lua",
  },
  ["luac"] = {
    icon = "",
    color = "#366b8a",
    cterm_color = "24",
    name = "Lua",
  },
  ["luau"] = {
    icon = "",
    color = "#007abf",
    cterm_color = "32",
    name = "Luau",
  },
  ["m3u"] = {
    icon = "󰲹",
    color = "#764a57",
    cterm_color = "95",
    name = "M3u",
  },
  ["m3u8"] = {
    icon = "󰲹",
    color = "#764a57",
    cterm_color = "95",
    name = "M3u8",
  },
  ["m4a"] = {
    icon = "",
    color = "#0075aa",
    cterm_color = "24",
    name = "MPEG4",
  },
  ["m4v"] = {
    icon = "",
    color = "#7e4c10",
    cterm_color = "94",
    name = "M4V",
  },
  ["magnet"] = {
    icon = "",
    color = "#a51b16",
    cterm_color = "124",
    name = "Magnet",
  },
  ["makefile"] = {
    icon = "",
    color = "#526064",
    cterm_color = "59",
    name = "Makefile",
  },
  ["markdown"] = {
    icon = "",
    color = "#4a4a4a",
    cterm_color = "239",
    name = "Markdown",
  },
  ["material"] = {
    icon = "󰔉",
    color = "#8a2b72",
    cterm_color = "89",
    name = "Material",
  },
  ["md"] = {
    icon = "",
    color = "#4a4a4a",
    cterm_color = "239",
    name = "Md",
  },
  ["md5"] = {
    icon = "󰕥",
    color = "#5d5975",
    cterm_color = "60",
    name = "Md5",
  },
  ["mdx"] = {
    icon = "",
    color = "#36677c",
    cterm_color = "24",
    name = "Mdx",
  },
  ["mint"] = {
    icon = "󰌪",
    color = "#44604a",
    cterm_color = "23",
    name = "Mint",
  },
  ["mjs"] = {
    icon = "",
    color = "#504b1e",
    cterm_color = "58",
    name = "Mjs",
  },
  ["mk"] = {
    icon = "",
    color = "#526064",
    cterm_color = "59",
    name = "Makefile",
  },
  ["mkv"] = {
    icon = "",
    color = "#7e4c10",
    cterm_color = "94",
    name = "Mkv",
  },
  ["ml"] = {
    icon = "",
    color = "#975122",
    cterm_color = "130",
    name = "Ml",
  },
  ["mli"] = {
    icon = "",
    color = "#975122",
    cterm_color = "130",
    name = "Mli",
  },
  ["m"] = {
    icon = "",
    color = "#3b69aa",
    cterm_color = "25",
    name = "ObjectiveC",
  },
  ["mm"] = {
    icon = "",
    color = "#36677c",
    cterm_color = "24",
    name = "ObjectiveCPlusPlus",
  },
  ["mo"] = {
    icon = "∞",
    color = "#654ca7",
    cterm_color = "61",
    name = "Motoko",
  },
  ["mobi"] = {
    icon = "",
    color = "#755836",
    cterm_color = "94",
    name = "Mobi",
  },
  ["mov"] = {
    icon = "",
    color = "#7e4c10",
    cterm_color = "94",
    name = "MOV",
  },
  ["mp3"] = {
    icon = "",
    color = "#0075aa",
    cterm_color = "24",
    name = "MPEGAudioLayerIII",
  },
  ["mp4"] = {
    icon = "",
    color = "#7e4c10",
    cterm_color = "94",
    name = "Mp4",
  },
  ["mpp"] = {
    icon = "",
    color = "#36677c",
    cterm_color = "24",
    name = "Mpp",
  },
  ["msf"] = {
    icon = "",
    color = "#0e5ca9",
    cterm_color = "25",
    name = "Thunderbird",
  },
  ["mts"] = {
    icon = "",
    color = "#36677c",
    cterm_color = "24",
    name = "Mts",
  },
  ["mustache"] = {
    icon = "",
    color = "#975122",
    cterm_color = "130",
    name = "Mustache",
  },
  ["nfo"] = {
    icon = "",
    color = "#333329",
    cterm_color = "236",
    name = "Nfo",
  },
  ["nim"] = {
    icon = "",
    color = "#514700",
    cterm_color = "58",
    name = "Nim",
  },
  ["nix"] = {
    icon = "",
    color = "#3f5d72",
    cterm_color = "24",
    name = "Nix",
  },
  ["nswag"] = {
    icon = "",
    color = "#427516",
    cterm_color = "28",
    name = "Nswag",
  },
  ["nu"] = {
    icon = ">",
    color = "#276f4e",
    cterm_color = "29",
    name = "Nushell",
  },
  ["o"] = {
    icon = "",
    color = "#9F0500",
    cterm_color = "124",
    name = "ObjectFile",
  },
  ["obj"] = {
    icon = "󰆧",
    color = "#5b5b5b",
    cterm_color = "240",
    name = "3DObjectFile",
  },
  ["ogg"] = {
    icon = "",
    color = "#005880",
    cterm_color = "24",
    name = "OggVorbis",
  },
  ["opus"] = {
    icon = "",
    color = "#005880",
    cterm_color = "24",
    name = "OpusAudioFile",
  },
  ["org"] = {
    icon = "",
    color = "#4f7166",
    cterm_color = "66",
    name = "OrgMode",
  },
  ["otf"] = {
    icon = "",
    color = "#2f2f2f",
    cterm_color = "236",
    name = "OpenTypeFont",
  },
  ["out"] = {
    icon = "",
    color = "#9F0500",
    cterm_color = "124",
    name = "Out",
  },
  ["part"] = {
    icon = "",
    color = "#226654",
    cterm_color = "23",
    name = "Part",
  },
  ["patch"] = {
    icon = "",
    color = "#41535b",
    cterm_color = "239",
    name = "Patch",
  },
  ["pck"] = {
    icon = "",
    color = "#526064",
    cterm_color = "59",
    name = "PackedResource",
  },
  ["pdf"] = {
    icon = "",
    color = "#b30b00",
    cterm_color = "124",
    name = "Pdf",
  },
  ["php"] = {
    icon = "",
    color = "#6b4d83",
    cterm_color = "96",
    name = "Php",
  },
  ["pl"] = {
    icon = "",
    color = "#36677c",
    cterm_color = "24",
    name = "Pl",
  },
  ["pls"] = {
    icon = "󰲹",
    color = "#764a57",
    cterm_color = "95",
    name = "Pls",
  },
  ["ply"] = {
    icon = "󰆧",
    color = "#5b5b5b",
    cterm_color = "240",
    name = "3DObjectFile",
  },
  ["pm"] = {
    icon = "",
    color = "#36677c",
    cterm_color = "24",
    name = "Pm",
  },
  ["png"] = {
    icon = "",
    color = "#6b4d83",
    cterm_color = "96",
    name = "Png",
  },
  ["po"] = {
    icon = "",
    color = "#1c708e",
    cterm_color = "24",
    name = "Localization",
  },
  ["pot"] = {
    icon = "",
    color = "#1c708e",
    cterm_color = "24",
    name = "Localization",
  },
  ["pp"] = {
    icon = "",
    color = "#80530d",
    cterm_color = "94",
    name = "Pp",
  },
  ["ppt"] = {
    icon = "󰈧",
    color = "#983826",
    cterm_color = "124",
    name = "Ppt",
  },
  ["prisma"] = {
    icon = "",
    color = "#444da2",
    cterm_color = "61",
    name = "Prisma",
  },
  ["pro"] = {
    icon = "",
    color = "#725c2a",
    cterm_color = "94",
    name = "Prolog",
  },
  ["ps1"] = {
    icon = "󰨊",
    color = "#325698",
    cterm_color = "25",
    name = "PsScriptfile",
  },
  ["psd1"] = {
    icon = "󰨊",
    color = "#4f5893",
    cterm_color = "60",
    name = "PsManifestfile",
  },
  ["psm1"] = {
    icon = "󰨊",
    color = "#4f5893",
    cterm_color = "60",
    name = "PsScriptModulefile",
  },
  ["psb"] = {
    icon = "",
    color = "#36677c",
    cterm_color = "24",
    name = "Psb",
  },
  ["psd"] = {
    icon = "",
    color = "#36677c",
    cterm_color = "24",
    name = "Psd",
  },
  ["pub"] = {
    icon = "󰷖",
    color = "#4c422f",
    cterm_color = "238",
    name = "Pub",
  },
  ["pxd"] = {
    icon = "",
    color = "#3c6f98",
    cterm_color = "24",
    name = "Pxd",
  },
  ["pxi"] = {
    icon = "",
    color = "#3c6f98",
    cterm_color = "24",
    name = "Pxi",
  },
  ["py"] = {
    icon = "",
    color = "#805e02",
    cterm_color = "94",
    name = "Py",
  },
  ["pyc"] = {
    icon = "",
    color = "#332d1d",
    cterm_color = "236",
    name = "Pyc",
  },
  ["pyd"] = {
    icon = "",
    color = "#332d1d",
    cterm_color = "236",
    name = "Pyd",
  },
  ["pyi"] = {
    icon = "",
    color = "#805e02",
    cterm_color = "94",
    name = "Pyi",
  },
  ["pyo"] = {
    icon = "",
    color = "#332d1d",
    cterm_color = "236",
    name = "Pyo",
  },
  ["pyx"] = {
    icon = "",
    color = "#3c6f98",
    cterm_color = "24",
    name = "Pyx",
  },
  ["qm"] = {
    icon = "",
    color = "#1c708e",
    cterm_color = "24",
    name = "Localization",
  },
  ["qml"] = {
    icon = "",
    color = "#2b8937",
    cterm_color = "28",
    name = "Qt",
  },
  ["qrc"] = {
    icon = "",
    color = "#2b8937",
    cterm_color = "28",
    name = "Qt",
  },
  ["qss"] = {
    icon = "",
    color = "#2b8937",
    cterm_color = "28",
    name = "Qt",
  },
  ["query"] = {
    icon = "",
    color = "#607035",
    cterm_color = "58",
    name = "Query",
  },
  ["r"] = {
    icon = "󰟔",
    color = "#1a4c8c",
    cterm_color = "25",
    name = "R",
  },
  ["rake"] = {
    icon = "",
    color = "#701516",
    cterm_color = "52",
    name = "Rake",
  },
  ["rar"] = {
    icon = "",
    color = "#76520c",
    cterm_color = "94",
    name = "Rar",
  },
  ["razor"] = {
    icon = "󱦘",
    color = "#512bd4",
    cterm_color = "56",
    name = "RazorPage",
  },
  ["rb"] = {
    icon = "",
    color = "#701516",
    cterm_color = "52",
    name = "Rb",
  },
  ["res"] = {
    icon = "",
    color = "#992e33",
    cterm_color = "88",
    name = "ReScript",
  },
  ["resi"] = {
    icon = "",
    color = "#a33759",
    cterm_color = "125",
    name = "ReScriptInterface",
  },
  ["rlib"] = {
    icon = "",
    color = "#6f5242",
    cterm_color = "95",
    name = "Rlib",
  },
  ["rmd"] = {
    icon = "",
    color = "#36677c",
    cterm_color = "24",
    name = "Rmd",
  },
  ["rproj"] = {
    icon = "󰗆",
    color = "#286844",
    cterm_color = "29",
    name = "Rproj",
  },
  ["rs"] = {
    icon = "",
    color = "#6f5242",
    cterm_color = "95",
    name = "Rs",
  },
  ["rss"] = {
    icon = "",
    color = "#7e4e1e",
    cterm_color = "94",
    name = "Rss",
  },
  ["sass"] = {
    icon = "",
    color = "#a33759",
    cterm_color = "125",
    name = "Sass",
  },
  ["sbt"] = {
    icon = "",
    color = "#992e33",
    cterm_color = "88",
    name = "sbt",
  },
  ["scad"] = {
    icon = "",
    color = "#53480f",
    cterm_color = "58",
    name = "OpenSCAD",
  },
  ["scala"] = {
    icon = "",
    color = "#992e33",
    cterm_color = "88",
    name = "Scala",
  },
  ["sc"] = {
    icon = "",
    color = "#992e33",
    cterm_color = "88",
    name = "ScalaScript",
  },
  ["scm"] = {
    icon = "󰘧",
    color = "#303030",
    cterm_color = "236",
    name = "Scheme",
  },
  ["scss"] = {
    icon = "",
    color = "#a33759",
    cterm_color = "125",
    name = "Scss",
  },
  ["sh"] = {
    icon = "",
    color = "#3a4446",
    cterm_color = "238",
    name = "Sh",
  },
  ["sha1"] = {
    icon = "󰕥",
    color = "#5d5975",
    cterm_color = "60",
    name = "Sha1",
  },
  ["sha224"] = {
    icon = "󰕥",
    color = "#5d5975",
    cterm_color = "60",
    name = "Sha224",
  },
  ["sha256"] = {
    icon = "󰕥",
    color = "#5d5975",
    cterm_color = "60",
    name = "Sha256",
  },
  ["sha384"] = {
    icon = "󰕥",
    color = "#5d5975",
    cterm_color = "60",
    name = "Sha384",
  },
  ["sha512"] = {
    icon = "󰕥",
    color = "#5d5975",
    cterm_color = "60",
    name = "Sha512",
  },
  ["sig"] = {
    icon = "λ",
    color = "#975122",
    cterm_color = "130",
    name = "Sig",
  },
  ["signature"] = {
    icon = "λ",
    color = "#975122",
    cterm_color = "130",
    name = "Signature",
  },
  ["skp"] = {
    icon = "󰻫",
    color = "#576342",
    cterm_color = "58",
    name = "SketchUp",
  },
  ["sldasm"] = {
    icon = "󰻫",
    color = "#576342",
    cterm_color = "58",
    name = "SolidWorksAsm",
  },
  ["sldprt"] = {
    icon = "󰻫",
    color = "#576342",
    cterm_color = "58",
    name = "SolidWorksPrt",
  },
  ["slim"] = {
    icon = "",
    color = "#aa391c",
    cterm_color = "124",
    name = "Slim",
  },
  ["sln"] = {
    icon = "",
    color = "#643995",
    cterm_color = "91",
    name = "Sln",
  },
  ["slvs"] = {
    icon = "󰻫",
    color = "#576342",
    cterm_color = "58",
    name = "SolveSpace",
  },
  ["sml"] = {
    icon = "λ",
    color = "#975122",
    cterm_color = "130",
    name = "Sml",
  },
  ["so"] = {
    icon = "",
    color = "#494a47",
    cterm_color = "239",
    name = "SharedObject",
  },
  ["sol"] = {
    icon = "",
    color = "#36677c",
    cterm_color = "24",
    name = "Solidity",
  },
  ["spec.js"] = {
    icon = "",
    color = "#666620",
    cterm_color = "58",
    name = "SpecJs",
  },
  ["spec.jsx"] = {
    icon = "",
    color = "#158197",
    cterm_color = "31",
    name = "JavaScriptReactSpec",
  },
  ["spec.ts"] = {
    icon = "",
    color = "#36677c",
    cterm_color = "24",
    name = "SpecTs",
  },
  ["spec.tsx"] = {
    icon = "",
    color = "#1354bf",
    cterm_color = "26",
    name = "TypeScriptReactSpec",
  },
  ["sql"] = {
    icon = "",
    color = "#494848",
    cterm_color = "238",
    name = "Sql",
  },
  ["sqlite"] = {
    icon = "",
    color = "#494848",
    cterm_color = "238",
    name = "Sql",
  },
  ["sqlite3"] = {
    icon = "",
    color = "#494848",
    cterm_color = "238",
    name = "Sql",
  },
  ["srt"] = {
    icon = "󰨖",
    color = "#805c0a",
    cterm_color = "94",
    name = "Srt",
  },
  ["ssa"] = {
    icon = "󰨖",
    color = "#805c0a",
    cterm_color = "94",
    name = "Ssa",
  },
  ["stl"] = {
    icon = "󰆧",
    color = "#5b5b5b",
    cterm_color = "240",
    name = "3DObjectFile",
  },
  ["strings"] = {
    icon = "",
    color = "#1c708e",
    cterm_color = "24",
    name = "Localization",
  },
  ["ste"] = {
    icon = "󰻫",
    color = "#576342",
    cterm_color = "58",
    name = "Ste",
  },
  ["step"] = {
    icon = "󰻫",
    color = "#576342",
    cterm_color = "58",
    name = "Step",
  },
  ["stp"] = {
    icon = "󰻫",
    color = "#576342",
    cterm_color = "58",
    name = "Stp",
  },
  ["styl"] = {
    icon = "",
    color = "#466024",
    cterm_color = "22",
    name = "Styl",
  },
  ["sub"] = {
    icon = "󰨖",
    color = "#805c0a",
    cterm_color = "94",
    name = "Sub",
  },
  ["sublime"] = {
    icon = "",
    color = "#975122",
    cterm_color = "130",
    name = "Sublime",
  },
  ["suo"] = {
    icon = "",
    color = "#643995",
    cterm_color = "91",
    name = "Suo",
  },
  ["sv"] = {
    icon = "󰍛",
    color = "#017226",
    cterm_color = "22",
    name = "SystemVerilog",
  },
  ["svelte"] = {
    icon = "",
    color = "#bf2e00",
    cterm_color = "160",
    name = "Svelte",
  },
  ["svh"] = {
    icon = "󰍛",
    color = "#017226",
    cterm_color = "22",
    name = "SystemVerilog",
  },
  ["svg"] = {
    icon = "󰜡",
    color = "#80581e",
    cterm_color = "94",
    name = "Svg",
  },
  ["swift"] = {
    icon = "",
    color = "#975122",
    cterm_color = "130",
    name = "Swift",
  },
  ["t"] = {
    icon = "",
    color = "#36677c",
    cterm_color = "24",
    name = "Tor",
  },
  ["tbc"] = {
    icon = "󰛓",
    color = "#1e5cb3",
    cterm_color = "25",
    name = "Tcl",
  },
  ["tcl"] = {
    icon = "󰛓",
    color = "#1e5cb3",
    cterm_color = "25",
    name = "Tcl",
  },
  ["templ"] = {
    icon = "",
    color = "#6e5e18",
    cterm_color = "58",
    name = "Templ",
  },
  ["terminal"] = {
    icon = "",
    color = "#217929",
    cterm_color = "28",
    name = "Terminal",
  },
  ["test.js"] = {
    icon = "",
    color = "#666620",
    cterm_color = "58",
    name = "TestJs",
  },
  ["test.jsx"] = {
    icon = "",
    color = "#158197",
    cterm_color = "31",
    name = "JavaScriptReactTest",
  },
  ["test.ts"] = {
    icon = "",
    color = "#36677c",
    cterm_color = "24",
    name = "TestTs",
  },
  ["test.tsx"] = {
    icon = "",
    color = "#1354bf",
    cterm_color = "26",
    name = "TypeScriptReactTest",
  },
  ["tex"] = {
    icon = "",
    color = "#3D6117",
    cterm_color = "22",
    name = "Tex",
  },
  ["tf"] = {
    icon = "",
    color = "#4732af",
    cterm_color = "55",
    name = "Terraform",
  },
  ["tfvars"] = {
    icon = "",
    color = "#4732af",
    cterm_color = "55",
    name = "TFVars",
  },
  ["tgz"] = {
    icon = "",
    color = "#76520c",
    cterm_color = "94",
    name = "Tgz",
  },
  ["toml"] = {
    icon = "",
    color = "#753219",
    cterm_color = "88",
    name = "Toml",
  },
  ["torrent"] = {
    icon = "",
    color = "#226654",
    cterm_color = "23",
    name = "Torrent",
  },
  ["tres"] = {
    icon = "",
    color = "#526064",
    cterm_color = "59",
    name = "GodotTextResource",
  },
  ["ts"] = {
    icon = "",
    color = "#36677c",
    cterm_color = "24",
    name = "Ts",
  },
  ["tscn"] = {
    icon = "",
    color = "#526064",
    cterm_color = "59",
    name = "GodotTextScene",
  },
  ["tsconfig"] = {
    icon = "",
    color = "#aa5a00",
    cterm_color = "130",
    name = "TypoScriptConfig",
  },
  ["tsx"] = {
    icon = "",
    color = "#1354bf",
    cterm_color = "26",
    name = "Tsx",
  },
  ["ttf"] = {
    icon = "",
    color = "#2f2f2f",
    cterm_color = "236",
    name = "TrueTypeFont",
  },
  ["twig"] = {
    icon = "",
    color = "#466024",
    cterm_color = "22",
    name = "Twig",
  },
  ["txz"] = {
    icon = "",
    color = "#76520c",
    cterm_color = "94",
    name = "Txz",
  },
  ["typoscript"] = {
    icon = "",
    color = "#aa5a00",
    cterm_color = "130",
    name = "TypoScript",
  },
  ["txt"] = {
    icon = "󰈙",
    color = "#447028",
    cterm_color = "22",
    name = "Txt",
  },
  ["ui"] = {
    icon = "",
    color = "#0c306e",
    cterm_color = "17",
    name = "UI",
  },
  ["v"] = {
    icon = "󰍛",
    color = "#017226",
    cterm_color = "22",
    name = "Verilog",
  },
  ["vala"] = {
    icon = "",
    color = "#562b86",
    cterm_color = "54",
    name = "Vala",
  },
  ["vh"] = {
    icon = "󰍛",
    color = "#017226",
    cterm_color = "22",
    name = "Verilog",
  },
  ["vhd"] = {
    icon = "󰍛",
    color = "#017226",
    cterm_color = "22",
    name = "VHDL",
  },
  ["vhdl"] = {
    icon = "󰍛",
    color = "#017226",
    cterm_color = "22",
    name = "VHDL",
  },
  ["vim"] = {
    icon = "",
    color = "#017226",
    cterm_color = "22",
    name = "Vim",
  },
  ["vsh"] = {
    icon = "",
    color = "#3e5a7f",
    cterm_color = "24",
    name = "Vlang",
  },
  ["vsix"] = {
    icon = "",
    color = "#643995",
    cterm_color = "91",
    name = "Vsix",
  },
  ["vue"] = {
    icon = "",
    color = "#466024",
    cterm_color = "22",
    name = "Vue",
  },
  ["wasm"] = {
    icon = "",
    color = "#4539a4",
    cterm_color = "55",
    name = "Wasm",
  },
  ["wav"] = {
    icon = "",
    color = "#0075aa",
    cterm_color = "24",
    name = "WaveformAudioFile",
  },
  ["webm"] = {
    icon = "",
    color = "#7e4c10",
    cterm_color = "94",
    name = "Webm",
  },
  ["webmanifest"] = {
    icon = "",
    color = "#504b1e",
    cterm_color = "58",
    name = "Webmanifest",
  },
  ["webp"] = {
    icon = "",
    color = "#6b4d83",
    cterm_color = "96",
    name = "Webp",
  },
  ["webpack"] = {
    icon = "󰜫",
    color = "#36677c",
    cterm_color = "24",
    name = "Webpack",
  },
  ["wma"] = {
    icon = "",
    color = "#0075aa",
    cterm_color = "24",
    name = "WindowsMediaAudio",
  },
  ["woff"] = {
    icon = "",
    color = "#2f2f2f",
    cterm_color = "236",
    name = "WebOpenFontFormat",
  },
  ["woff2"] = {
    icon = "",
    color = "#2f2f2f",
    cterm_color = "236",
    name = "WebOpenFontFormat",
  },
  ["wrl"] = {
    icon = "󰆧",
    color = "#5b5b5b",
    cterm_color = "240",
    name = "VRML",
  },
  ["wrz"] = {
    icon = "󰆧",
    color = "#5b5b5b",
    cterm_color = "240",
    name = "VRML",
  },
  ["x"] = {
    icon = "",
    color = "#3b69aa",
    cterm_color = "25",
    name = "Logos",
  },
  ["xm"] = {
    icon = "",
    color = "#36677c",
    cterm_color = "24",
    name = "Logos",
  },
  ["xaml"] = {
    icon = "󰙳",
    color = "#512bd4",
    cterm_color = "56",
    name = "Xaml",
  },
  ["xcf"] = {
    icon = "",
    color = "#4a4434",
    cterm_color = "238",
    name = "GIMP",
  },
  ["xcplayground"] = {
    icon = "",
    color = "#975122",
    cterm_color = "130",
    name = "XcPlayground",
  },
  ["xcstrings"] = {
    icon = "",
    color = "#1c708e",
    cterm_color = "24",
    name = "XcLocalization",
  },
  ["xls"] = {
    icon = "󰈛",
    color = "#207245",
    cterm_color = "29",
    name = "Xls",
  },
  ["xlsx"] = {
    icon = "󰈛",
    color = "#207245",
    cterm_color = "29",
    name = "Xlsx",
  },
  ["xml"] = {
    icon = "󰗀",
    color = "#975122",
    cterm_color = "130",
    name = "Xml",
  },
  ["xpi"] = {
    icon = "",
    color = "#bf1401",
    cterm_color = "124",
    name = "Xpi",
  },
  ["xul"] = {
    icon = "",
    color = "#975122",
    cterm_color = "130",
    name = "Xul",
  },
  ["xz"] = {
    icon = "",
    color = "#76520c",
    cterm_color = "94",
    name = "Xz",
  },
  ["yaml"] = {
    icon = "",
    color = "#526064",
    cterm_color = "59",
    name = "Yaml",
  },
  ["yml"] = {
    icon = "",
    color = "#526064",
    cterm_color = "59",
    name = "Yml",
  },
  ["zig"] = {
    icon = "",
    color = "#7b4d0e",
    cterm_color = "94",
    name = "Zig",
  },
  ["zip"] = {
    icon = "",
    color = "#76520c",
    cterm_color = "94",
    name = "Zip",
  },
  ["zsh"] = {
    icon = "",
    color = "#447028",
    cterm_color = "22",
    name = "Zsh",
  },
  ["zst"] = {
    icon = "",
    color = "#76520c",
    cterm_color = "94",
    name = "Zst",
  },
}

local icons_by_operating_system = {
  ["apple"] = {
    icon = "",
    color = "#515556",
    cterm_color = "240",
    name = "Apple",
  },
  ["windows"] = {
    icon = "",
    color = "#007bb3",
    cterm_color = "67",
    name = "Windows",
  },
  ["linux"] = {
    icon = "",
    color = "#333332",
    cterm_color = "236",
    name = "Linux",
  },
  ["alma"] = {
    icon = "",
    color = "#bf3437",
    cterm_color = "160",
    name = "Almalinux",
  },
  ["alpine"] = {
    icon = "",
    color = "#0d597f",
    cterm_color = "24",
    name = "Alpine",
  },
  ["aosc"] = {
    icon = "",
    color = "#c00000",
    cterm_color = "124",
    name = "AOSC",
  },
  ["arch"] = {
    icon = "󰣇",
    color = "#0b6f9e",
    cterm_color = "24",
    name = "Arch",
  },
  ["archcraft"] = {
    icon = "",
    color = "#435e52",
    cterm_color = "23",
    name = "Archcraft",
  },
  ["archlabs"] = {
    icon = "",
    color = "#503f42",
    cterm_color = "238",
    name = "Archlabs",
  },
  ["arcolinux"] = {
    icon = "",
    color = "#44609d",
    cterm_color = "25",
    name = "ArcoLinux",
  },
  ["artix"] = {
    icon = "",
    color = "#2b788f",
    cterm_color = "31",
    name = "Artix",
  },
  ["biglinux"] = {
    icon = "",
    color = "#127796",
    cterm_color = "31",
    name = "BigLinux",
  },
  ["centos"] = {
    icon = "",
    color = "#7a3d6a",
    cterm_color = "89",
    name = "Centos",
  },
  ["crystallinux"] = {
    icon = "",
    color = "#a900ff",
    cterm_color = "129",
    name = "CrystalLinux",
  },
  ["debian"] = {
    icon = "",
    color = "#a80030",
    cterm_color = "88",
    name = "Debian",
  },
  ["deepin"] = {
    icon = "",
    color = "#1d6fa5",
    cterm_color = "24",
    name = "Deepin",
  },
  ["devuan"] = {
    icon = "",
    color = "#404a52",
    cterm_color = "238",
    name = "Devuan",
  },
  ["elementary"] = {
    icon = "",
    color = "#3b6081",
    cterm_color = "24",
    name = "Elementary",
  },
  ["endeavour"] = {
    icon = "",
    color = "#5c2e8b",
    cterm_color = "54",
    name = "Endeavour",
  },
  ["fedora"] = {
    icon = "",
    color = "#072a5e",
    cterm_color = "17",
    name = "Fedora",
  },
  ["freebsd"] = {
    icon = "",
    color = "#c90f02",
    cterm_color = "160",
    name = "FreeBSD",
  },
  ["garuda"] = {
    icon = "",
    color = "#1f57a9",
    cterm_color = "25",
    name = "GarudaLinux",
  },
  ["gentoo"] = {
    icon = "󰣨",
    color = "#585667",
    cterm_color = "60",
    name = "Gentoo",
  },
  ["guix"] = {
    icon = "",
    color = "#554400",
    cterm_color = "58",
    name = "Guix",
  },
  ["hyperbola"] = {
    icon = "",
    color = "#404040",
    cterm_color = "238",
    name = "HyperbolaGNULinuxLibre",
  },
  ["illumos"] = {
    icon = "",
    color = "#bf320b",
    cterm_color = "160",
    name = "Illumos",
  },
  ["kali"] = {
    icon = "",
    color = "#1d59bf",
    cterm_color = "26",
    name = "Kali",
  },
  ["kdeneon"] = {
    icon = "",
    color = "#187c7b",
    cterm_color = "30",
    name = "KDEneon",
  },
  ["kubuntu"] = {
    icon = "",
    color = "#005c92",
    cterm_color = "24",
    name = "Kubuntu",
  },
  ["locos"] = {
    icon = "",
    color = "#7d5a01",
    cterm_color = "94",
    name = "LocOS",
  },
  ["lxle"] = {
    icon = "",
    color = "#474747",
    cterm_color = "238",
    name = "LXLE",
  },
  ["mint"] = {
    icon = "󰣭",
    color = "#447529",
    cterm_color = "28",
    name = "Mint",
  },
  ["mageia"] = {
    icon = "",
    color = "#1a719f",
    cterm_color = "24",
    name = "Mageia",
  },
  ["manjaro"] = {
    icon = "",
    color = "#227b3b",
    cterm_color = "29",
    name = "Manjaro",
  },
  ["mxlinux"] = {
    icon = "",
    color = "#333333",
    cterm_color = "236",
    name = "MXLinux",
  },
  ["nixos"] = {
    icon = "",
    color = "#3d586e",
    cterm_color = "24",
    name = "NixOS",
  },
  ["openbsd"] = {
    icon = "",
    color = "#514310",
    cterm_color = "58",
    name = "OpenBSD",
  },
  ["opensuse"] = {
    icon = "",
    color = "#4a7818",
    cterm_color = "64",
    name = "openSUSE",
  },
  ["parabola"] = {
    icon = "",
    color = "#515373",
    cterm_color = "60",
    name = "ParabolaGNULinuxLibre",
  },
  ["parrot"] = {
    icon = "",
    color = "#2a6f80",
    cterm_color = "23",
    name = "Parrot",
  },
  ["pop_os"] = {
    icon = "",
    color = "#307b85",
    cterm_color = "30",
    name = "Pop_OS",
  },
  ["postmarketos"] = {
    icon = "",
    color = "#007300",
    cterm_color = "22",
    name = "postmarketOS",
  },
  ["puppylinux"] = {
    icon = "",
    color = "#51575c",
    cterm_color = "240",
    name = "PuppyLinux",
  },
  ["qubesos"] = {
    icon = "",
    color = "#2957a2",
    cterm_color = "25",
    name = "QubesOS",
  },
  ["raspberry_pi"] = {
    icon = "",
    color = "#be1848",
    cterm_color = "161",
    name = "RaspberryPiOS",
  },
  ["redhat"] = {
    icon = "󱄛",
    color = "#EE0000",
    cterm_color = "196",
    name = "Redhat",
  },
  ["rocky"] = {
    icon = "",
    color = "#0b865e",
    cterm_color = "29",
    name = "RockyLinux",
  },
  ["sabayon"] = {
    icon = "",
    color = "#424242",
    cterm_color = "238",
    name = "Sabayon",
  },
  ["slackware"] = {
    icon = "",
    color = "#35477f",
    cterm_color = "25",
    name = "Slackware",
  },
  ["solus"] = {
    icon = "",
    color = "#4b5163",
    cterm_color = "239",
    name = "Solus",
  },
  ["tails"] = {
    icon = "",
    color = "#56347c",
    cterm_color = "54",
    name = "Tails",
  },
  ["trisquel"] = {
    icon = "",
    color = "#0f58b6",
    cterm_color = "25",
    name = "TrisquelGNULinux",
  },
  ["ubuntu"] = {
    icon = "",
    color = "#a6360f",
    cterm_color = "124",
    name = "Ubuntu",
  },
  ["vanillaos"] = {
    icon = "",
    color = "#533f1a",
    cterm_color = "58",
    name = "VanillaOS",
  },
  ["void"] = {
    icon = "",
    color = "#295340",
    cterm_color = "23",
    name = "Void",
  },
  ["xerolinux"] = {
    icon = "",
    color = "#5b5f97",
    cterm_color = "60",
    name = "XeroLinux",
  },
  ["zorin"] = {
    icon = "",
    color = "#0f79ae",
    cterm_color = "67",
    name = "Zorin",
  },
}

local icons_by_desktop_environment = {
  ["budgie"] = {
    icon = "",
    color = "#4e5361",
    cterm_color = "240",
    name = "Budgie",
  },
  ["cinnamon"] = {
    icon = "",
    color = "#93451f",
    cterm_color = "124",
    name = "Cinnamon",
  },
  ["gnome"] = {
    icon = "",
    color = "#333333",
    cterm_color = "236",
    name = "GNOME",
  },
  ["lxde"] = {
    icon = "",
    color = "#525252",
    cterm_color = "239",
    name = "LXDE",
  },
  ["lxqt"] = {
    icon = "",
    color = "#016d9e",
    cterm_color = "24",
    name = "LXQt",
  },
  ["mate"] = {
    icon = "",
    color = "#4e6d2e",
    cterm_color = "22",
    name = "MATE",
  },
  ["plasma"] = {
    icon = "",
    color = "#1467b7",
    cterm_color = "25",
    name = "KDEPlasma",
  },
  ["xfce"] = {
    icon = "",
    color = "#0080a7",
    cterm_color = "31",
    name = "Xfce",
  },
}

local icons_by_window_manager = {
  ["awesomewm"] = {
    icon = "",
    color = "#3e4651",
    cterm_color = "238",
    name = "awesome",
  },
  ["bspwm"] = {
    icon = "",
    color = "#4f4f4f",
    cterm_color = "239",
    name = "BSPWM",
  },
  ["dwm"] = {
    icon = "",
    color = "#0d5980",
    cterm_color = "24",
    name = "dwm",
  },
  ["enlightenment"] = {
    icon = "",
    color = "#333333",
    cterm_color = "236",
    name = "Enlightenment",
  },
  ["fluxbox"] = {
    icon = "",
    color = "#404040",
    cterm_color = "238",
    name = "Fluxbox",
  },
  ["hyprland"] = {
    icon = "",
    color = "#008082",
    cterm_color = "30",
    name = "Hyprland",
  },
  ["i3"] = {
    icon = "",
    color = "#2e2f30",
    cterm_color = "236",
    name = "i3",
  },
  ["jwm"] = {
    icon = "",
    color = "#005a9a",
    cterm_color = "25",
    name = "JWM",
  },
  ["qtile"] = {
    icon = "",
    color = "#333333",
    cterm_color = "236",
    name = "Qtile",
  },
  ["sway"] = {
    icon = "",
    color = "#4e5815",
    cterm_color = "58",
    name = "Sway",
  },
  ["xmonad"] = {
    icon = "",
    color = "#a9333e",
    cterm_color = "131",
    name = "xmonad",
  },
}

return {
  icons_by_filename = icons_by_filename,
  icons_by_file_extension = icons_by_file_extension,
  icons_by_operating_system = icons_by_operating_system,
  icons_by_desktop_environment = icons_by_desktop_environment,
  icons_by_window_manager = icons_by_window_manager,
}
